import { describe, expect, it } from "vitest";
import { decideDocket, docketCommand, overlaps } from "./docket";

const context = { tenantId: "t", userId: "u", roles: ["attorney"], matterAccess: new Set(["m"]) };
const fixture = { action: "materialize_fixture_docket" as const, tenantId: "t", matterId: "m", seriesId: "series-1", hearingEventId: "hearing-1", preparationEventId: "prep-1", recurringEventIds: ["call-1", "call-2", "call-3"], conflictingEventId: "depo-1", dependencyId: "dependency-1", reminderId: "reminder-1", conflictId: "conflict-1", syncStateId: "sync-1", ownerId: "owner-1", hearingStart: "2026-09-18T15:30:00.000Z", hearingEnd: "2026-09-18T17:00:00.000Z", preparationStart: "2026-09-16T23:00:00.000Z", preparationEnd: "2026-09-17T00:00:00.000Z", recurringStart: "2026-09-01T17:00:00.000Z", recurringEnd: "2026-09-01T17:30:00.000Z", conflictStart: "2026-09-01T17:15:00.000Z", conflictEnd: "2026-09-01T18:00:00.000Z", timezone: "America/Los_Angeles" as const, sandboxAcknowledged: true as const, idempotencyKey: "docket-fixture" };

describe("calendar docket lifecycle", () => {
  it("materializes a locally expanded docket without provider claims", () => expect(decideDocket({ context, raw: fixture }).event.payload).toMatchObject({ microsoftConnected: false, providerWriteAttempted: false, recurrenceExpandedLocally: true }));
  it("detects half-open interval overlap", () => { expect(overlaps(fixture.recurringStart, fixture.recurringEnd, fixture.conflictStart, fixture.conflictEnd)).toBe(true); expect(overlaps(fixture.recurringStart, fixture.recurringEnd, fixture.recurringEnd, fixture.conflictEnd)).toBe(false); });
  it("rejects invalid preparation chronology", () => expect(() => docketCommand.parse({ ...fixture, preparationEnd: fixture.hearingStart })).toThrow("precede"));
  it("requires open conflicts and scheduled reminders", () => { expect(() => decideDocket({ context, conflict: { id: "conflict-1", status: "accepted_with_reason", revision: 1 }, raw: { action: "resolve_conflict", tenantId: "t", matterId: "m", conflictId: "conflict-1", expectedRevision: 1, resolution: "reschedule_required", reason: "Owner must select a new deposition time.", idempotencyKey: "docket-conflict" } })).toThrow("open"); expect(() => decideDocket({ context, reminder: { id: "reminder-1", status: "acknowledged", revision: 1 }, raw: { action: "acknowledge_reminder", tenantId: "t", matterId: "m", reminderId: "reminder-1", expectedRevision: 1, reason: "Attorney reviewed the reminder and docket source.", idempotencyKey: "docket-reminder" } })).toThrow("scheduled"); });
  it("enforces revision and tenant isolation", () => { expect(() => decideDocket({ context, syncState: { id: "sync-1", status: "not_connected", providerMode: "not_connected", revision: 1 }, raw: { action: "record_sync_block", tenantId: "t", matterId: "m", syncStateId: "sync-1", expectedRevision: 2, reason: "Microsoft credentials and tenant consent remain unavailable.", idempotencyKey: "docket-sync" } })).toThrow("changed"); expect(() => decideDocket({ context, raw: { ...fixture, tenantId: "other" } })).toThrow("Access denied"); });
});
