import { Activity, ClipboardList, Gavel, Stethoscope } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { MetricGrid, ModuleHeader, WorkstreamTable } from "@/components/module-layout";
const rows=[
 {primary:"Rivera — QME supplemental request",secondary:"Medical record cutoff and service proof required",owner:"Maya Chen",due:"Due Aug 22",status:"Needs review",tone:"warning" as const},
 {primary:"Cruz — DOR / MSC packet",secondary:"Venue and service list verified",owner:"Sara Kim",due:"Due Aug 21",status:"Approval gate",tone:"danger" as const},
 {primary:"Nguyen — deposition logistics",secondary:"Interpreter and reporter confirmation",owner:"Jon Bell",due:"Aug 21 · 1:00 PM",status:"Confirmed",tone:"success" as const},
];
export default function CaliforniaOperationsPage(){return <AppShell><div className="simple-page"><ModuleHeader eyebrow="CALIFORNIA OPERATIONS" title="Workers’ compensation control center" description="Medical-legal workflow, proceedings, deadlines, authority, settlement, and closure controls for California defense matters." /><div className="truth-banner"><Gavel size={18}/><div><strong>EAMS remains an external system of record</strong><p>Athena does not claim direct EAMS filing or docket sync in this environment. Human verification remains required.</p></div></div><MetricGrid metrics={[{label:"QME actions",value:"7",detail:"Next 14 days",icon:Stethoscope},{label:"Proceedings",value:"6",detail:"Next 30 days",icon:Gavel},{label:"Medical records",value:"12",detail:"Review queue",icon:Activity},{label:"Closure checklists",value:"4",detail:"In progress",icon:ClipboardList}]} /><WorkstreamTable title="California operations queue" description="Operational tasks are source-linked and remain subject to attorney review." rows={rows} /></div></AppShell>}
