import { decideRetentionControl, retentionControlCommand } from "@/domain/platform/retention-controls";
import { evaluateRetention } from "@/domain/platform/retention-policy";
import { authorizePersistedMatter } from "@/platform/access-policy-persistence";
import { GOLDEN_MATTER_ID,PILOT_TENANT_ID,pilotContext } from "@/platform/pilot-context";
import { readPlatformPolicies } from "@/platform/platform-policy-persistence";
import { enforceRateLimit,RateLimitError,rateLimitResponse } from "@/platform/rate-limit-persistence";
import { requestActor } from "@/platform/request-actor";
import { assertTrustedWriteOrigin,RequestSecurityError } from "@/platform/request-security";
import { listLegalHolds,listRetentionReviews,persistRetentionControl,readLegalHold } from "@/platform/retention-control-persistence";
import { AuthorizationError,requireRole } from "@/platform/tenant-context";

async function projection(){const policies=await readPlatformPolicies(PILOT_TENANT_ID,GOLDEN_MATTER_ID);const evaluation=evaluateRetention({createdAt:new Date("2026-08-20T00:00:00Z"),asOf:new Date(),policy:policies.retention,activeLegalHold:policies.activeLegalHold});return{holds:await listLegalHolds(PILOT_TENANT_ID,GOLDEN_MATTER_ID),reviews:await listRetentionReviews(PILOT_TENANT_ID,GOLDEN_MATTER_ID),evaluation,limitation:"No automatic deletion path exists. Eligibility permits only a human escalation review; it never deletes records or R2 objects."};}
export async function GET(request:Request){try{const actor=requestActor(request);if(!actor)return Response.json({error:"Authentication required"},{status:401});const context=pilotContext(actor);requireRole(context,["partner","firm_admin"]);await authorizePersistedMatter(context,PILOT_TENANT_ID,GOLDEN_MATTER_ID);return Response.json(await projection());}catch(e){if(e instanceof AuthorizationError)return Response.json({error:"Access denied"},{status:403});return Response.json({error:"Retention controls could not be read"},{status:500});}}
export async function POST(request:Request){try{assertTrustedWriteOrigin(request);const actor=requestActor(request);if(!actor)return Response.json({error:"Authentication required"},{status:401});await enforceRateLimit({tenantId:PILOT_TENANT_ID,actorId:actor.userId,action:"retention.command",policy:{limit:10,windowMs:60_000}});const context=pilotContext(actor),command=retentionControlCommand.parse(await request.json());await authorizePersistedMatter(context,command.tenantId,command.matterId);const policies=await readPlatformPolicies(command.tenantId,command.matterId);const evaluation=command.action==="record_review"?evaluateRetention({createdAt:new Date("2026-08-20T00:00:00Z"),asOf:new Date(),policy:policies.retention,activeLegalHold:policies.activeLegalHold}):undefined;const current=command.action==="release_hold"?await readLegalHold(command.tenantId,command.matterId,command.holdId):undefined;const decision=decideRetentionControl({context,raw:command,currentHold:current,evaluation});const persistence=await persistRetentionControl({...decision,actor,evaluation});return Response.json({event:decision.event,persistence,...await projection()});}catch(e){if(e instanceof RateLimitError)return rateLimitResponse(e);if(e instanceof RequestSecurityError)return Response.json({error:"Untrusted request origin"},{status:403});if(e instanceof AuthorizationError)return Response.json({error:"Access denied"},{status:403});return Response.json({error:e instanceof Error?e.message:"Retention command failed"},{status:400});}}
