import { decideStructuredAuthority, structuredAuthorityCommand, type StructuredAuthorityResponseState, type StructuredAuthorityState } from "@/domain/authority/structured-approval";
import { persistStructuredAuthority, readStructuredAuthorityEvent, readStructuredAuthorityRequest, readStructuredAuthorityResponse, structuredAuthorityProjection } from "@/platform/structured-authority-persistence";
import { GOLDEN_MATTER_ID, PILOT_TENANT_ID, pilotContext } from "@/platform/pilot-context";
import { enforceRateLimit, RateLimitError, rateLimitResponse } from "@/platform/rate-limit-persistence";
import { requestActor } from "@/platform/request-actor";
import { assertTrustedWriteOrigin, RequestSecurityError } from "@/platform/request-security";
import { AuthorizationError } from "@/platform/tenant-context";
const limitation = "Athena persists an attorney-authored structured authority request, approval, honest secure-page delivery block, human-verified external response, confirmed authority ledger entry, supersession, and expiration task. No secure approval page, invitation, external login, email delivery, examiner signature, notification, or provider reconciliation exists.";
export async function GET(request: Request) { try { const actor = requestActor(request); if (!actor) return Response.json({ error: "Authentication required" }, { status: 401 }); const context = pilotContext(actor); if (!context.matterAccess.has(GOLDEN_MATTER_ID)) throw new AuthorizationError(); return Response.json({ ...(await structuredAuthorityProjection(PILOT_TENANT_ID, GOLDEN_MATTER_ID)), limitation }); } catch (error) { if (error instanceof AuthorizationError) return Response.json({ error: "Access denied" }, { status: 403 }); return Response.json({ error: "Structured authority requests could not be read" }, { status: 500 }); } }
export async function POST(request: Request) { try {
  assertTrustedWriteOrigin(request); const actor = requestActor(request); if (!actor) return Response.json({ error: "Authentication required" }, { status: 401 });
  await enforceRateLimit({ tenantId: PILOT_TENANT_ID, actorId: actor.userId, action: "structured_authority.command", policy: { limit: 20, windowMs: 60000 } });
  const context = pilotContext(actor), command = structuredAuthorityCommand.parse(await request.json()), prior = await readStructuredAuthorityEvent(command.tenantId, command.idempotencyKey);
  if (prior) return Response.json({ persistence: { replayed: true, eventId: prior.eventId }, ...(await structuredAuthorityProjection(command.tenantId, command.matterId)), limitation });
  const current = await readStructuredAuthorityRequest(command.tenantId, command.matterId, command.requestId), response = command.action === "confirm_response" ? await readStructuredAuthorityResponse(command.tenantId, command.matterId, command.responseId) : null;
  const decision = decideStructuredAuthority({ context, raw: command, current: current as StructuredAuthorityState | null, response: response as StructuredAuthorityResponseState | null }), persistence = await persistStructuredAuthority({ ...decision, actor });
  return Response.json({ event: decision.event, persistence, ...(await structuredAuthorityProjection(command.tenantId, command.matterId)), limitation });
} catch (error) { if (error instanceof RateLimitError) return rateLimitResponse(error); if (error instanceof RequestSecurityError) return Response.json({ error: "Untrusted request origin" }, { status: 403 }); if (error instanceof AuthorizationError) return Response.json({ error: "Access denied" }, { status: 403 }); return Response.json({ error: error instanceof Error ? error.message : "Structured authority command failed" }, { status: 400 }); } }
