import{z}from"zod";import{createEvent}from"@/platform/events";import{authorizeMatter,requireRole,type TenantContext}from"@/platform/tenant-context";const base={tenantId:z.string().min(1),matterId:z.string().min(1),idempotencyKey:z.string().min(8).max(200)},id=z.string().min(3).max(160),revision=z.number().int().positive(),evidence=z.string().trim().min(12).max(1500),page=z.number().int().positive();
export const documentEvidenceCommand=z.discriminatedUnion("action",[
 z.object({action:z.literal("materialize_fixture_original"),...base,evidenceId:id,title:z.string().min(5).max(240),privilege:z.enum(["none","attorney_client","work_product"]),confidentiality:z.enum(["public","internal","confidential","highly_confidential"]),sandboxAcknowledged:z.literal(true)}),
 z.object({action:z.literal("create_derivative"),...base,evidenceId:id,derivativeId:id,parentDerivativeId:id.optional(),derivativeKind:z.enum(["redacted_copy","bates_copy","medical_index","exhibit_version","filing_copy","final_attorney_approved"]),title:z.string().min(5).max(240),sourcePageStart:page,sourcePageEnd:page,providerMode:z.enum(["deterministic_sandbox","human_authored"])}),
 z.object({action:z.literal("record_provider_block"),...base,evidenceId:id,derivativeId:id,derivativeKind:z.enum(["ocr_text","ai_summary"]),reason:evidence}),
 z.object({action:z.literal("approve_derivative"),...base,evidenceId:id,derivativeId:id,reason:evidence}),
 z.object({action:z.literal("assign_bates"),...base,evidenceId:id,derivativeId:id,assignmentId:id,prefix:z.string().regex(/^[A-Z0-9-]{2,20}$/),startNumber:z.number().int().positive(),digits:z.number().int().min(4).max(10)}),
 z.object({action:z.literal("assign_exhibit"),...base,evidenceId:id,derivativeId:id,assignmentId:id,proceedingId:id,exhibitLabel:z.string().regex(/^[A-Z0-9-]{1,20}$/),description:z.string().min(5).max(500)}),
 z.object({action:z.literal("create_production_set"),...base,productionSetId:id,title:z.string().min(5).max(240),purpose:z.string().min(12).max(1000)}),
 z.object({action:z.literal("add_production_item"),...base,productionSetId:id,expectedRevision:revision,itemId:id,evidenceId:id,derivativeId:id,position:z.number().int().positive(),includedPageStart:page,includedPageEnd:page,privilegeReviewed:z.literal(true),confidentialityReviewed:z.literal(true)}),
 z.object({action:z.literal("validate_production_set"),...base,productionSetId:id,expectedRevision:revision}),
 z.object({action:z.literal("approve_production_set"),...base,productionSetId:id,expectedRevision:revision,reason:evidence}),
 z.object({action:z.literal("finalize_production_set"),...base,productionSetId:id,expectedRevision:revision}),
]);export type DocumentEvidenceCommand=z.infer<typeof documentEvidenceCommand>;export type EvidenceState={id:string;pageCount:number;originalSha256:string;originalObjectKey:string};export type DerivativeState={id:string;evidenceId:string;status:"draft"|"approved"|"blocked";derivativeKind:string;version:number;sourcePageStart:number;sourcePageEnd:number;sha256?:string|null;objectKey?:string|null};export type ProductionSetState={id:string;status:"draft"|"validated"|"approved"|"export_ready";revision:number;items:Array<{evidenceId:string;derivativeId:string;position:number;includedPageStart:number;includedPageEnd:number;privilegeReviewed:boolean;confidentialityReviewed:boolean;derivativeStatus:string}>};
export function validateProductionSet(set:ProductionSetState){const positions=[...set.items].sort((a,b)=>a.position-b.position).map(x=>x.position),checks=[{code:"items",status:set.items.length>0?"pass":"fail",explanation:"At least one derivative is required."},{code:"positions",status:set.items.length>0&&positions.every((x,i)=>x===i+1)?"pass":"fail",explanation:"Positions must be contiguous from one."},{code:"approved_derivatives",status:set.items.every(x=>x.derivativeStatus==="approved")?"pass":"fail",explanation:"Every included derivative must be approved."},{code:"privilege_review",status:set.items.every(x=>x.privilegeReviewed)?"pass":"fail",explanation:"Every item requires privilege review."},{code:"confidentiality_review",status:set.items.every(x=>x.confidentialityReviewed)?"pass":"fail",explanation:"Every item requires confidentiality review."}]as const;return{outcome:checks.some(x=>x.status==="fail")?"fail"as const:"pass"as const,checks,itemCount:set.items.length,pageCount:set.items.reduce((n,x)=>n+x.includedPageEnd-x.includedPageStart+1,0)}}
export function decideDocumentEvidence(input:{context:TenantContext;raw:unknown;evidence?:EvidenceState|null;derivative?:DerivativeState|null;productionSet?:ProductionSetState|null;validation?:ReturnType<typeof validateProductionSet>;targetExists?:boolean}){const command=documentEvidenceCommand.parse(input.raw);authorizeMatter(input.context,command.tenantId,command.matterId);requireRole(input.context,["attorney","partner","paralegal","legal_assistant"]);let aggregateType="document_evidence",aggregateId="evidenceId"in command?command.evidenceId:command.productionSetId,fromStatus="not_created",toStatus="recorded";
 if(command.action==="materialize_fixture_original"){if(input.evidence)throw new Error("Original evidence identity already exists");toStatus="trusted_synthetic_fixture";}
 else if(command.action==="create_derivative"){if(!input.evidence)throw new Error("Original evidence does not exist");if(input.targetExists)throw new Error("Derivative identity already exists");if(command.sourcePageEnd<command.sourcePageStart||command.sourcePageEnd>input.evidence.pageCount)throw new Error("Derivative page range exceeds the original");toStatus="draft";}
 else if(command.action==="record_provider_block"){if(!input.evidence)throw new Error("Original evidence does not exist");if(input.targetExists)throw new Error("Derivative identity already exists");toStatus="blocked";}
 else if(command.action==="approve_derivative"){if(!input.derivative||input.derivative.evidenceId!==command.evidenceId||input.derivative.status!=="draft")throw new Error("Only a draft derivative in this lineage can be approved");fromStatus="draft";toStatus="approved";}
 else if(command.action==="assign_bates"){if(!input.derivative||input.derivative.status!=="approved")throw new Error("Bates assignment requires an approved derivative");aggregateType="bates_assignment";aggregateId=command.assignmentId;toStatus="assigned";}
 else if(command.action==="assign_exhibit"){if(!input.derivative||input.derivative.status!=="approved")throw new Error("Exhibit assignment requires an approved derivative");aggregateType="exhibit_assignment";aggregateId=command.assignmentId;toStatus="assigned";}
 else if(command.action==="create_production_set"){aggregateType="production_set";aggregateId=command.productionSetId;if(input.productionSet)throw new Error("Production set already exists");toStatus="draft";}
 else{aggregateType="production_set";aggregateId=command.productionSetId;const set=input.productionSet;if(!set||set.revision!==command.expectedRevision)throw new Error("Production set changed; refresh before retrying");fromStatus=set.status;if(command.action==="add_production_item"){if(set.status!=="draft"||!input.derivative||input.derivative.status!=="approved"||input.derivative.evidenceId!==command.evidenceId)throw new Error("Only an approved derivative can be added to a draft production set");if(command.includedPageEnd<command.includedPageStart||command.includedPageStart<input.derivative.sourcePageStart||command.includedPageEnd>input.derivative.sourcePageEnd)throw new Error("Included pages exceed derivative lineage");toStatus="draft";}else if(command.action==="validate_production_set"){if(set.status!=="draft"||input.validation?.outcome!=="pass")throw new Error("Production set failed validation");toStatus="validated";}else if(command.action==="approve_production_set"){requireRole(input.context,["attorney","partner"]);if(set.status!=="validated")throw new Error("Only a validated production set can be approved");toStatus="approved";}else{if(set.status!=="approved")throw new Error("Only an approved production set can be finalized");toStatus="export_ready";}}
 const event=createEvent({eventType:`document_evidence.${command.action}`,tenantId:command.tenantId,aggregateType,aggregateId,matterId:command.matterId,actorId:input.context.userId,correlationId:command.idempotencyKey,idempotencyKey:command.idempotencyKey,source:"athena.web",visibility:"restricted",retentionPolicy:"matter-lifecycle-plus-firm-retention",payload:{action:command.action,fromStatus,toStatus,originalMutated:false,ocrConnected:false,aiConnected:false,humanAuthorized:true}});return{command,aggregateType,aggregateId,fromStatus,toStatus,event}}
