import { describe, expect, it } from "vitest";
import { decideStructuredAuthority, type StructuredAuthorityResponseState, type StructuredAuthorityState } from "./structured-approval";
import { AuthorizationError, type TenantContext } from "@/platform/tenant-context";
const context: TenantContext = { tenantId: "t", userId: "attorney-1", roles: ["attorney"], matterAccess: new Set(["matter-1"]) }, base = { tenantId: "t", matterId: "matter-1", requestId: "request-1", idempotencyKey: "structured-authority-test-001" }, now = new Date("2026-08-20T12:00:00.000Z");
const current = (status: StructuredAuthorityState["status"], revision = 1): StructuredAuthorityState => ({ id: "request-1", status, revision, requestedExpiresAt: new Date("2026-09-30T12:00:00.000Z") });
const response: StructuredAuthorityResponseState = { id: "response-1", outcome: "modified", amountCents: 9000000, settlementStructure: "C&R", scope: "Resolve all claims at MSC", effectiveAt: new Date("2026-08-20T12:00:00.000Z"), expiresAt: new Date("2026-09-30T12:00:00.000Z"), negotiationThresholdCents: 7500000 };
describe("structured authority approval", () => {
  it("blocks delivery without claiming a secure page or transmission", () => { const x = decideStructuredAuthority({ context, current: current("approved_for_delivery"), now, raw: { action: "attempt_delivery", ...base, expectedRevision: 1, reason: "Secure client approval identity and delivery are unavailable." } }); expect(x.toStatus).toBe("delivery_blocked"); expect(x.event.payload).toMatchObject({ secureApprovalPageEnabled: false, deliveryAttempted: false }); });
  it("requires complete approved or modified terms and valid thresholds", () => { expect(() => decideStructuredAuthority({ context, current: current("delivery_blocked"), now, raw: { action: "record_human_response", ...base, expectedRevision: 1, responseId: "response-1", outcome: "modified", amountCents: 9000000, currency: "USD", negotiationThresholdCents: 9500000, responderName: "Jennifer Smith", responderRole: "Claims examiner", responderOrganization: "Summit Claims", evidence: "Attorney verified the synthetic response outside the disconnected portal." } })).toThrow(); });
  it("confirms only a complete non-declined verified response", () => { expect(decideStructuredAuthority({ context, current: current("response_recorded"), response, now, raw: { action: "confirm_response", ...base, expectedRevision: 1, responseId: "response-1", ledgerId: "ledger-1", candidateId: "candidate-1", expirationTaskId: "task-1", reason: "Attorney verified every structured response term and source evidence." } }).toStatus).toBe("confirmed"); expect(() => decideStructuredAuthority({ context, current: current("response_recorded"), response: { ...response, outcome: "declined" }, now, raw: { action: "confirm_response", ...base, expectedRevision: 1, responseId: "response-1", ledgerId: "ledger-1", candidateId: "candidate-1", expirationTaskId: "task-1", reason: "A declined response can never create active authority." } })).toThrow(); });
  it("enforces attorney role, tenant, matter, and expiry", () => { expect(() => decideStructuredAuthority({ context: { ...context, roles: ["paralegal"] }, current: current("draft"), now, raw: { action: "approve_request", ...base, expectedRevision: 1, reason: "Staff cannot approve a structured authority request." } })).toThrow(AuthorizationError); expect(() => decideStructuredAuthority({ context, current: current("draft"), now, raw: { action: "approve_request", ...base, tenantId: "other", expectedRevision: 1, reason: "Foreign tenant authority requests must be rejected." } })).toThrow(AuthorizationError); expect(() => decideStructuredAuthority({ context, current: current("draft"), now, raw: { action: "approve_request", ...base, matterId: "other", expectedRevision: 1, reason: "Foreign matter authority requests must be rejected." } })).toThrow(AuthorizationError); });
});
