import { clientInstructionCommand, decideClientInstruction } from "@/domain/governance/client-instruction";
import { authorizePersistedMatter } from "@/platform/access-policy-persistence";
import { clientInstructionProjection, listClientInstructionReviews, persistClientInstruction, readClientInstruction, readClientInstructionEvent } from "@/platform/client-instruction-persistence";
import { OptimisticConcurrencyError } from "@/platform/optimistic-concurrency";
import { GOLDEN_MATTER_ID, PILOT_TENANT_ID, pilotContext } from "@/platform/pilot-context";
import { enforceRateLimit, RateLimitError, rateLimitResponse } from "@/platform/rate-limit-persistence";
import { requestActor } from "@/platform/request-actor";
import { assertTrustedWriteOrigin, RequestSecurityError } from "@/platform/request-security";
import { AuthorizationError } from "@/platform/tenant-context";
const limitation = "This workflow uses a checksum-pinned synthetic client-instruction PDF and can activate only synthetic sandbox policy. Verified external client evidence ingestion is not connected, so Athena does not claim a real client instruction is active.";
async function projection() { return { ...await clientInstructionProjection(PILOT_TENANT_ID, GOLDEN_MATTER_ID), limitation }; }
export async function GET(request: Request) { try { const actor = requestActor(request); if (!actor) return Response.json({ error: "Authentication required" }, { status: 401 }); const context = pilotContext(actor); await authorizePersistedMatter(context, PILOT_TENANT_ID, GOLDEN_MATTER_ID); return Response.json(await projection()); } catch (error) { if (error instanceof AuthorizationError) return Response.json({ error: "Access denied" }, { status: 403 }); return Response.json({ error: "Client instruction evidence could not be read" }, { status: 500 }); } }
export async function POST(request: Request) { try { assertTrustedWriteOrigin(request); const actor = requestActor(request); if (!actor) return Response.json({ error: "Authentication required" }, { status: 401 }); await enforceRateLimit({ tenantId: PILOT_TENANT_ID, actorId: actor.userId, action: "client-instruction.command", policy: { limit: 20, windowMs: 60_000 } }); const context = pilotContext(actor), command = clientInstructionCommand.parse(await request.json()); await authorizePersistedMatter(context, command.tenantId, command.matterId); const prior = await readClientInstructionEvent(command.tenantId, command.idempotencyKey); if (prior) return Response.json({ event: null, persistence: { replayed: true, eventId: prior.eventId }, ...await projection() }); const current = command.action === "materialize_synthetic_source" ? null : await readClientInstruction(command.tenantId, command.matterId, command.instructionId), reviews = command.action === "materialize_synthetic_source" ? [] : await listClientInstructionReviews(command.tenantId, command.matterId, command.instructionId); const decision = decideClientInstruction({ context, raw: command, current, reviews }); const persistence = await persistClientInstruction({ ...decision, actor }); return Response.json({ event: decision.event, persistence, ...await projection() }); } catch (error) { if (error instanceof RateLimitError) return rateLimitResponse(error); if (error instanceof RequestSecurityError) return Response.json({ error: "Untrusted request origin" }, { status: 403 }); if (error instanceof AuthorizationError) return Response.json({ error: "Access denied" }, { status: 403 }); if (error instanceof OptimisticConcurrencyError || (error instanceof Error && error.message.startsWith("Client instruction changed;"))) return Response.json({ error: "Record changed; refresh before retrying" }, { status: 409 }); return Response.json({ error: error instanceof Error ? error.message : "Client instruction command failed" }, { status: 400 }); } }
