import { describe,expect,it } from "vitest";
import { decideProceeding,evaluateProceedingReadiness,proceedingItemCodes,proceedingItemDefinitions,type ProceedingItemState } from "./readiness";
const items=(status:"missing"|"verified"="verified"):ProceedingItemState[]=>proceedingItemCodes.map(code=>({...proceedingItemDefinitions[code],code,status,revision:1}));
const context={tenantId:"tenant-a",userId:"user-a",roles:["attorney" as const],matterAccess:new Set(["matter-a"])};
describe("proceeding readiness",()=>{
  it("blocks when critical internal evidence is missing",()=>{const x=items();x.find(y=>y.code==="medical_records")!.status="missing";expect(evaluateProceedingReadiness(x)).toMatchObject({state:"blocked",nonAutonomous:true})});
  it("reports an honest external dependency when only disconnected filing verification remains",()=>{const x=items();x.find(y=>y.code==="filing_status")!.status="missing";const result=evaluateProceedingReadiness(x);expect(result.state).toBe("external_dependency");expect(result.findings.find(y=>y.code==="filing_status")).toMatchObject({status:"blocked",category:"external_dependency"})});
  it("returns ready only after every required item has evidence",()=>expect(evaluateProceedingReadiness(items())).toMatchObject({state:"ready",passCount:12,gapCount:0,blockedCount:0,nonAutonomous:true}));
  it("requires client action when authority is the remaining gap",()=>{const x=items();x.find(y=>y.code==="authority")!.status="missing";expect(evaluateProceedingReadiness(x,true).state).toBe("client_decision_required")});
  it("rejects false native EAMS evidence and cross-tenant commands",()=>{const filing=items().find(x=>x.code==="filing_status")!;filing.status="missing";expect(()=>decideProceeding({context,exists:true,item:filing,raw:{action:"verify_item",tenantId:"tenant-a",matterId:"matter-a",proceedingId:"p-1",itemCode:"filing_status",expectedRevision:1,evidence:"Court receipt was manually inspected.",evidenceType:"human_attestation",evidenceId:"receipt-1",providerMode:"athena_native",idempotencyKey:"proceeding-proof"}})).toThrow("human_verified_external");expect(()=>decideProceeding({context,exists:false,raw:{action:"create",tenantId:"tenant-b",matterId:"matter-a",proceedingId:"p-1",proceedingType:"msc",title:"Mandatory settlement conference",scheduledAt:"2026-10-10T17:00:00.000Z",venue:"WCAB Oakland",sourceType:"attorney_entry",sourceId:"source-1",contentStatus:"pending_attorney_review",idempotencyKey:"proceeding-create"}})).toThrow("Access denied")});
});
