import { decideFilingPacket,filingPacketCommand } from "@/domain/filings/packet";
import { authorizePersistedMatter } from "@/platform/access-policy-persistence";
import { buildFilingPacketEvaluation,filingPacketProjection,persistFilingPacket,readFilingPacket,readFilingPacketEvent } from "@/platform/filing-packet-persistence";
import { GOLDEN_MATTER_ID,PILOT_TENANT_ID,pilotContext } from "@/platform/pilot-context";
import { enforceRateLimit,RateLimitError,rateLimitResponse } from "@/platform/rate-limit-persistence";
import { requestActor } from "@/platform/request-actor";
import { assertTrustedWriteOrigin,RequestSecurityError } from "@/platform/request-security";
import { AuthorizationError } from "@/platform/tenant-context";
const limitation="Native packet preparation and validation are active in a synthetic California sandbox. EAMS/JET is disconnected; handoff blocks honestly, and return status requires human-verified external evidence.";
export async function GET(request:Request){try{const actor=requestActor(request);if(!actor)return Response.json({error:"Authentication required"},{status:401});await authorizePersistedMatter(pilotContext(actor),PILOT_TENANT_ID,GOLDEN_MATTER_ID);return Response.json({...await filingPacketProjection(PILOT_TENANT_ID,GOLDEN_MATTER_ID),limitation});}catch(e){if(e instanceof AuthorizationError)return Response.json({error:"Access denied"},{status:403});return Response.json({error:"Filing packets could not be read"},{status:500});}}
export async function POST(request:Request){try{assertTrustedWriteOrigin(request);const actor=requestActor(request);if(!actor)return Response.json({error:"Authentication required"},{status:401});await enforceRateLimit({tenantId:PILOT_TENANT_ID,actorId:actor.userId,action:"filing_packets.command",policy:{limit:40,windowMs:60_000}});const context=pilotContext(actor),command=filingPacketCommand.parse(await request.json());await authorizePersistedMatter(context,command.tenantId,command.matterId);const prior=await readFilingPacketEvent(command.tenantId,command.idempotencyKey);if(prior)return Response.json({event:null,persistence:{replayed:true,eventId:prior.eventId},...await filingPacketProjection(command.tenantId,command.matterId),limitation});const current=await readFilingPacket(command.tenantId,command.matterId,command.packetId),evaluation=command.action==="validate"?await buildFilingPacketEvaluation(command.tenantId,command.matterId,command.packetId):undefined,correctedExists=command.action==="correct"?Boolean(await readFilingPacket(command.tenantId,command.matterId,command.correctedPacketId)):false,decision=decideFilingPacket({context,raw:command,current:current as never,evaluation,correctedExists}),persistence=await persistFilingPacket({...decision,actor,evaluation});return Response.json({event:decision.event,persistence,...await filingPacketProjection(command.tenantId,command.matterId),limitation});}catch(e){if(e instanceof RateLimitError)return rateLimitResponse(e);if(e instanceof RequestSecurityError)return Response.json({error:"Untrusted request origin"},{status:403});if(e instanceof AuthorizationError)return Response.json({error:"Access denied"},{status:403});return Response.json({error:e instanceof Error?e.message:"Filing packet command failed"},{status:400});}}
