import { BadgeDollarSign, Clock, ReceiptText, TriangleAlert } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { MetricGrid, ModuleHeader, WorkstreamTable } from "@/components/module-layout";
import { WorkflowDecision } from "@/components/workflow-decision";
const rows=[
 {primary:"Review QME report and identify disputed facts",secondary:"Rivera v. Northstar · 1.2h · A104",owner:"Maya Chen",due:"Captured 10:42 AM",status:"Needs confirmation",tone:"warning" as const},
 {primary:"Prepare MSC status update",secondary:"Cruz v. Ember · 0.8h · L210",owner:"Sara Kim",due:"Aug 19",status:"Ready",tone:"success" as const},
 {primary:"Deposition preparation",secondary:"Nguyen v. Arcadia · 2.4h · L330",owner:"Jon Bell",due:"Aug 19",status:"Guideline check",tone:"info" as const},
];
export default function BillingPage(){return <AppShell active="Billing"><div className="simple-page"><ModuleHeader eyebrow="TIME & BILLING" title="Billing control" description="Human-confirmed time, client guideline checks, invoice readiness, and immutable source context." /><MetricGrid metrics={[{label:"Unconfirmed time",value:"3.6h",detail:"3 entries",icon:Clock},{label:"Month to date",value:"$184,260",detail:"Synthetic",icon:BadgeDollarSign},{label:"Pre-bill exceptions",value:"7",detail:"Needs review",icon:TriangleAlert},{label:"Ready to invoice",value:"$42,810",detail:"12 matters",icon:ReceiptText}]} /><div className="module-two-column"><WorkstreamTable title="Time review" description="Athena may suggest narrative and codes, but a person confirms the billable record." rows={rows} column="Entry" /><aside className="panel decision-panel"><span className="eyebrow">TIME CONFIRMATION</span><h2>1.2 hours · Rivera matter</h2><p>Review QME report; analyze apportionment and permanent-disability conclusions; update matter posture.</p><dl><div><dt>Code</dt><dd>A104</dd></div><div><dt>Rate</dt><dd>$325/hr</dd></div><div><dt>Value</dt><dd>$390.00</dd></div></dl><WorkflowDecision workflowType="time" aggregateId="time-rivera-20260820-01" matterId="matter-golden" action="confirm" label="Confirm time entry" successLabel="Time confirmed" /></aside></div></div></AppShell>}
