import { expect, test, type APIRequestContext } from "@playwright/test";
const owner = { "oai-authenticated-user-id": "user-maya-chen", "oai-authenticated-user-email": "user-maya-chen@example.test", "oai-authenticated-user-full-name": encodeURIComponent("Maya Chen"), "oai-authenticated-user-full-name-encoding": "percent-encoded-utf-8" };
const reviewer = { "oai-authenticated-user-id": "user-client-reviewer", "oai-authenticated-user-email": "client-reviewer@example.test", "oai-authenticated-user-full-name": encodeURIComponent("Independent Client Reviewer"), "oai-authenticated-user-full-name-encoding": "percent-encoded-utf-8" };
const writeHeaders = (actor: Record<string, string>) => ({ ...actor, "content-type": "application/json", origin: "http://localhost:3000" });
async function instruction(request: APIRequestContext, actor: Record<string, string>, data: Record<string, unknown>) { return request.post("/api/admin/governance/client-instructions", { headers: writeHeaders(actor), data }); }
test("client-instruction activation pins source bytes, requires independent reviews, and activates only synthetic policy truth", async ({ request }) => {
  const suffix = `${Date.now()}-${test.info().workerIndex}`, instructionId = `client-instruction-e2e-${suffix}`, evidenceId = `client-instruction-evidence-${suffix}`, layerId = `client-instruction-layer-${suffix}`, code = `synthetic-client-status-report-deadline-${suffix}`, base = { tenantId: "tenant-golden", matterId: "matter-golden-001", instructionId };
  let response = await instruction(request, owner, { action: "materialize_synthetic_source", ...base, evidenceId, clientId: "client-summit", code, version: 1, title: "Synthetic Summit status-report instruction", businessDays: 6, authorityCitation: "Synthetic Summit workflow fixture — not an external client instruction.", effectiveDate: "2026-01-01", reviewDate: "2026-12-31", sandboxAcknowledged: true, idempotencyKey: `client-instruction-create-${suffix}` }); expect(response.status()).toBe(200);
  response = await instruction(request, owner, { action: "review_source", ...base, expectedRevision: 1, reviewId: `integrity-review-${suffix}`, reviewType: "source_integrity", outcome: "approved", evidence: "Reviewer matched the preserved PDF bytes, checksum, custody identity, and synthetic label.", idempotencyKey: `client-instruction-integrity-${suffix}` }); expect(response.status()).toBe(200);
  response = await instruction(request, reviewer, { action: "review_source", ...base, expectedRevision: 2, reviewId: `scope-review-${suffix}`, reviewType: "instruction_scope", outcome: "approved", evidence: "Independent reviewer confirmed the exact client, scope, dates, and six-day instruction.", idempotencyKey: `client-instruction-scope-${suffix}` }); expect(response.status()).toBe(200);
  const activate = (attempt: string) => instruction(request, attempt === "a" ? owner : reviewer, { action: "activate_source", ...base, expectedRevision: 3, layerId, approval: `Partner activation attempt ${attempt} after both independent checksum-matched reviews.`, idempotencyKey: `client-instruction-activate-${attempt}-${suffix}` });
  const raced = await Promise.all([activate("a"), activate("b")]); expect(raced.map(item => item.status()).sort()).toEqual([200, 409]); const winner = raced[0].status() === 200 ? "a" : "b"; const replay = await activate(winner); expect(replay.status()).toBe(200); expect((await replay.json() as { persistence: { replayed: boolean } }).persistence.replayed).toBe(true);
  let projection = await (await request.get("/api/admin/governance/client-instructions", { headers: owner })).json() as { sources: Array<{ id: string; status: string; revision: number; sourceSha256: string; activatedLayerId: string | null }>; reviews: Array<{ instructionId: string; reviewerId: string; reviewType: string }> };
  expect(projection.sources.find(item => item.id === instructionId)).toMatchObject({ status: "synthetic_active", revision: 4, activatedLayerId: layerId, sourceSha256: "de1eeca720928434efd1dd329447d2eae7653221ea18c15226cf576320ed7e09" });
  const reviews = projection.reviews.filter(item => item.instructionId === instructionId); expect(new Set(reviews.map(item => item.reviewerId)).size).toBe(2); expect(new Set(reviews.map(item => item.reviewType))).toEqual(new Set(["source_integrity", "instruction_scope"]));
  response = await request.post("/api/admin/governance", { headers: writeHeaders(owner), data: { action: "simulate", tenantId: "tenant-golden", matterId: "matter-golden-001", simulationId: `client-instruction-simulation-${suffix}`, code, triggerDate: "2026-08-20", asOfDate: "2026-08-21", clientId: "client-summit", matterType: "california-wc-defense", sandboxAcknowledged: true, idempotencyKey: `client-instruction-simulate-${suffix}` } }); expect(response.status()).toBe(200);
  const governance = await response.json() as { simulations: Array<{ id: string; selectedLayerId: string; dueAt: string }>; layers: Array<{ id: string; sourceKind: string; sourceId: string | null; sourceSha256: string | null; contentStatus: string; status: string }> };
  expect(governance.simulations.find(item => item.id === `client-instruction-simulation-${suffix}`)).toMatchObject({ selectedLayerId: layerId, dueAt: expect.stringContaining("2026-08-31") }); expect(governance.layers.find(item => item.id === layerId)).toMatchObject({ sourceKind: "client_instruction", sourceId: instructionId, sourceSha256: "de1eeca720928434efd1dd329447d2eae7653221ea18c15226cf576320ed7e09", contentStatus: "synthetic_sandbox", status: "active" });
  const deactivate = (attempt: string) => instruction(request, owner, { action: "deactivate_source", ...base, expectedRevision: 4, reason: `Partner deactivation attempt ${attempt} preserves history and disables derived policy.`, idempotencyKey: `client-instruction-deactivate-${attempt}-${suffix}` });
  const deactivations = await Promise.all([deactivate("a"), deactivate("b")]); expect(deactivations.map(item => item.status()).sort()).toEqual([200, 409]);
  projection = await (await request.get("/api/admin/governance/client-instructions", { headers: owner })).json() as typeof projection; expect(projection.sources.find(item => item.id === instructionId)).toMatchObject({ status: "deactivated", revision: 5 });
});
