import { expect, test, type APIRequestContext } from "@playwright/test";
const owner = { "oai-authenticated-user-id": "user-maya-chen", "oai-authenticated-user-email": "user-maya-chen@example.test", "oai-authenticated-user-full-name": encodeURIComponent("user-maya-chen"), "oai-authenticated-user-full-name-encoding": "percent-encoded-utf-8" };
const writeHeaders = { ...owner, "content-type": "application/json", origin: "http://localhost:3000" };
const sectionTemplates = [
  { sectionCode: "matter_identity", title: "Matter identity", body: "Synthetic Rivera matter, claim, and adjudication identity from scoped records.", sourceRecordIds: ["matter-golden-001", "claim-golden-001"] },
  { sectionCode: "current_posture", title: "Current posture", body: "Synthetic active posture and proceeding readiness from scoped matter records.", sourceRecordIds: ["proceeding-msc-golden-001"] },
  { sectionCode: "medical_status", title: "Medical status", body: "Checksum-pinned synthetic medical evidence with no production AI conclusion.", sourceRecordIds: ["evidence-qme-golden-001"] },
  { sectionCode: "authority", title: "Authority", body: "Attorney-reviewed synthetic authority ledger is the controlling source record.", sourceRecordIds: ["authority-candidate-125k"] },
  { sectionCode: "upcoming_events", title: "Upcoming events", body: "Local docket events, dependencies, and conflict evidence remain source linked.", sourceRecordIds: ["calendar-event-msc-001"] },
  { sectionCode: "legal_spend", title: "Legal spend", body: "Synthetic integer-cent invoice lifecycle supplies the legal spend evidence.", sourceRecordIds: ["invoice-golden-001"] },
];
async function recurring(request: APIRequestContext, data: Record<string, unknown>) { return request.post("/api/reports/recurrence", { headers: writeHeaders, data }); }
async function lifecycle(request: APIRequestContext, data: Record<string, unknown>) { return request.post("/api/reports/lifecycle", { headers: writeHeaders, data }); }

test("recurring reports create governed drafts that still require validation, approval, and honest delivery state", async ({ request }) => {
  const suffix = `${Date.now()}-${test.info().workerIndex}`, seriesId = `report-series-e2e-${suffix}`, base = { tenantId: "tenant-golden", matterId: "matter-golden-001", seriesId };
  let response = await recurring(request, { action: "create_series", ...base, definitionId: "report-definition-summit-recurring-v1", definitionCode: "SUMMIT-RECURRING-STATUS", titlePattern: "Recurring status — {due_date}", recipientAddresses: ["examiner@example.test"], sectionTemplates, cadence: "monthly", interval: 1, dayOfMonth: 31, startsOn: "2026-01-31", endsOn: "2026-04-30", occurrenceLimit: 4, timezone: "America/Los_Angeles", sandboxAcknowledged: true, idempotencyKey: `report-series-create-${suffix}` });
  expect(response.status()).toBe(200);
  response = await recurring(request, { action: "activate_series", ...base, expectedRevision: 1, approval: "Attorney approved recipients, source template, and bounded local schedule.", idempotencyKey: `report-series-activate-${suffix}` }); expect(response.status()).toBe(200);
  response = await recurring(request, { action: "set_exception", ...base, expectedRevision: 2, nominalDueOn: "2026-02-28", exceptionAction: "move", movedDueOn: "2026-03-02", reason: "Move this report to incorporate the scheduled medical status update.", idempotencyKey: `report-series-exception-${suffix}` }); expect(response.status()).toBe(200);
  const materialize = (attempt: string) => recurring(request, { action: "materialize_window", ...base, expectedRevision: 3, throughDate: "2026-04-30", idempotencyKey: `report-series-materialize-${attempt}-${suffix}` });
  const raced = await Promise.all([materialize("a"), materialize("b")]); expect(raced.map(item => item.status()).sort()).toEqual([200, 409]);
  const winner = raced[0].status() === 200 ? "a" : "b"; const replay = await materialize(winner); expect(replay.status()).toBe(200); expect((await replay.json() as { persistence: { replayed: boolean } }).persistence.replayed).toBe(true);
  const projection = await (await request.get("/api/reports/recurrence", { headers: owner })).json() as { series: Array<{ id: string; revision: number; materializedCount: number; status: string }>; occurrences: Array<{ seriesId: string; reportInstanceId: string | null; nominalDueOn: string; effectiveDueOn: string | null; exceptionAction: string }> };
  expect(projection.series.find(item => item.id === seriesId)).toMatchObject({ revision: 4, materializedCount: 4, status: "active" });
  const occurrences = projection.occurrences.filter(item => item.seriesId === seriesId); expect(occurrences.map(item => [item.nominalDueOn.slice(0, 10), item.effectiveDueOn?.slice(0, 10), item.exceptionAction])).toEqual([["2026-01-31", "2026-01-31", "none"], ["2026-02-28", "2026-03-02", "move"], ["2026-03-31", "2026-03-31", "none"], ["2026-04-30", "2026-04-30", "none"]]);
  const reportInstanceId = occurrences[0].reportInstanceId!;
  response = await lifecycle(request, { action: "validate_report", tenantId: "tenant-golden", matterId: "matter-golden-001", reportInstanceId, expectedRevision: 1, idempotencyKey: `recurring-report-validate-${suffix}` }); expect(response.status()).toBe(200);
  response = await lifecycle(request, { action: "approve_report", tenantId: "tenant-golden", matterId: "matter-golden-001", reportInstanceId, expectedRevision: 2, reason: "Attorney reviewed every recurring source-linked report section and recipient.", idempotencyKey: `recurring-report-approve-${suffix}` }); expect(response.status()).toBe(200);
  response = await lifecycle(request, { action: "record_delivery_block", tenantId: "tenant-golden", matterId: "matter-golden-001", reportInstanceId, expectedRevision: 3, deliveryId: `recurring-report-delivery-${suffix}`, reason: "Microsoft delivery credentials and reconciliation remain unavailable.", idempotencyKey: `recurring-report-block-${suffix}` }); expect(response.status()).toBe(200);
  const lifecycleProjection = await response.json() as { instances: Array<{ id: string; status: string }>; sections: Array<{ reportInstanceId: string; sourceRecordIds: string[] }>; deliveries: Array<{ reportInstanceId: string; providerDeliveryAttempted: boolean; status: string }> };
  expect(lifecycleProjection.instances.find(item => item.id === reportInstanceId)?.status).toBe("delivery_blocked"); expect(lifecycleProjection.sections.filter(item => item.reportInstanceId === reportInstanceId)).toHaveLength(6); expect(lifecycleProjection.deliveries.find(item => item.reportInstanceId === reportInstanceId)).toMatchObject({ providerDeliveryAttempted: false, status: "blocked_not_connected" });
  response = await recurring(request, { action: "cancel_series", ...base, expectedRevision: 4, reason: "Attorney ended future recurrence while preserving all created report drafts.", idempotencyKey: `report-series-cancel-${suffix}` }); expect(response.status()).toBe(200);
});
