import { describe, expect, it } from "vitest";
import type { TenantContext } from "@/platform/tenant-context";
import { decideRetentionControl } from "./retention-controls";

const context: TenantContext={tenantId:"tenant-a",userId:"partner-1",roles:["partner"],matterAccess:new Set(["matter-1"])};
describe("retention controls",()=>{
  it("places and releases legal holds with restricted events",()=>{const place=decideRetentionControl({context,raw:{action:"place_hold",tenantId:"tenant-a",matterId:"matter-1",name:"Litigation preservation",reason:"Preserve the complete file during pending litigation.",idempotencyKey:"hold-place-0001"}});expect(place.event).toMatchObject({eventType:"retention.legal_hold_placed",visibility:"restricted",payload:{automaticDeletion:false}});const release={action:"release_hold",tenantId:"tenant-a",matterId:"matter-1",holdId:"hold-1",expectedRevision:1,reason:"Litigation concluded and preservation release was approved.",idempotencyKey:"hold-release-0001"};expect(decideRetentionControl({context,raw:release,currentHold:{id:"hold-1",status:"active",revision:1}}).event.eventType).toBe("retention.legal_hold_released");expect(()=>decideRetentionControl({context,raw:release,currentHold:{id:"hold-1",status:"active",revision:2}})).toThrow(/refresh/);});
  it("blocks disposition escalation before eligibility and while held",()=>{const raw={action:"record_review",tenantId:"tenant-a",matterId:"matter-1",conclusion:"escalate_for_disposition_review",notes:"Reviewed the policy and preservation status with the partner.",idempotencyKey:"retention-review-0001"};expect(()=>decideRetentionControl({context,raw,evaluation:{outcome:"retain",reason:"Minimum period remains",policyCode:"firm",policyVersion:1}})).toThrow(/before eligibility/);expect(()=>decideRetentionControl({context,raw,evaluation:{outcome:"held",reason:"Active hold",policyCode:"firm",policyVersion:1}})).toThrow(/while held/);expect(decideRetentionControl({context,raw,evaluation:{outcome:"eligible_for_review",reason:"Period elapsed",policyCode:"firm",policyVersion:1}}).event.payload).toMatchObject({automaticDeletion:false});});
  it("requires an authorized administrator",()=>expect(()=>decideRetentionControl({context:{...context,roles:["attorney"]},raw:{action:"place_hold",tenantId:"tenant-a",matterId:"matter-1",name:"Litigation preservation",reason:"Preserve the complete file during pending litigation.",idempotencyKey:"hold-place-0002"}})).toThrow(/authorized legal reviewer/));
});
