import { describe, expect, it } from "vitest";
import { decideScaleAudit, measureLocalPerformance, scaleBlockingGaps } from "./scale-audit";
import { AuthorizationError, type TenantContext } from "@/platform/tenant-context";
const context: TenantContext = { tenantId: "t", userId: "partner-1", roles: ["partner"], matterAccess: new Set() };
describe("scale audit", () => {
  it("measures four local budgets and leaves deployed async budgets unproven", () => { let t = 0; const metrics = measureLocalPerformance(() => ++t); expect(metrics.filter((x) => x.status === "pass")).toHaveLength(4); expect(metrics.filter((x) => x.status === "not_measured").map((x) => x.metricCode)).toEqual(["event_availability", "background_job_ack"]); });
  it("never claims production readiness from local evidence", () => { const x = decideScaleAudit({ context, measurements: measureLocalPerformance(() => 1), raw: { action: "run_local_benchmark", tenantId: "t", assessmentId: "scale-1", workloadProfile: "Twenty-five thousand synthetic rows in one local Worker process.", maxPageSize: 100, outboxBatchLimit: 100, archiveByteLimit: 536870912, archiveRowLimit: 250000, idempotencyKey: "scale-test-001", syntheticAcknowledged: true } }); expect(x.event.payload).toMatchObject({ productionReady: false, representativeLoadProven: false, independentValidation: false }); });
  it("requires a partner and preserves blocking gaps on review", () => { expect(() => decideScaleAudit({ context: { ...context, roles: ["attorney"] }, current: { id: "scale-1", status: "measured", revision: 1, blockingGaps: scaleBlockingGaps }, raw: { action: "review_capacity", tenantId: "t", assessmentId: "scale-1", expectedRevision: 1, outcome: "accept_with_gaps", reason: "Accept only as local evidence with every production gap unresolved.", idempotencyKey: "scale-review-001" } })).toThrow(AuthorizationError); expect(decideScaleAudit({ context, current: { id: "scale-1", status: "measured", revision: 1, blockingGaps: scaleBlockingGaps }, raw: { action: "review_capacity", tenantId: "t", assessmentId: "scale-1", expectedRevision: 1, outcome: "accept_with_gaps", reason: "Accept only as local evidence with every production gap unresolved.", idempotencyKey: "scale-review-001" } }).toStatus).toBe("reviewed_with_gaps"); });
  it("enforces tenant isolation", () => expect(() => decideScaleAudit({ context, measurements: measureLocalPerformance(() => 1), raw: { action: "run_local_benchmark", tenantId: "other", assessmentId: "scale-1", workloadProfile: "Foreign tenant benchmark must be rejected before persistence.", maxPageSize: 100, outboxBatchLimit: 100, archiveByteLimit: 536870912, archiveRowLimit: 250000, idempotencyKey: "scale-test-002", syntheticAcknowledged: true } })).toThrow(AuthorizationError));
});
