import { describe, expect, it } from "vitest";
import { decideClientInstruction, type ClientInstructionState } from "./client-instruction";
import { buildSyntheticClientInstructionPdf, SYNTHETIC_CLIENT_INSTRUCTION_BYTE_SIZE, SYNTHETIC_CLIENT_INSTRUCTION_SHA256 } from "./synthetic-client-instruction";
const context = { tenantId: "tenant-test", userId: "reviewer-a", roles: ["partner" as const], matterAccess: new Set(["matter-test"]) };
const current: ClientInstructionState = { id: "instruction-1", clientId: "client-summit", evidenceId: "evidence-1", code: "synthetic-client-status-report-deadline-test", version: 1, sourceSha256: SYNTHETIC_CLIENT_INSTRUCTION_SHA256, sourceMode: "deterministic_sandbox", status: "under_review", revision: 2, businessDays: 6, authorityCitation: "Synthetic instruction fixture, not external client content.", effectiveAt: new Date("2026-01-01T12:00:00Z"), reviewBy: new Date("2026-12-31T12:00:00Z"), activatedLayerId: null };
const base = { tenantId: "tenant-test", matterId: "matter-test", instructionId: current.id, idempotencyKey: "client-instruction-test" };
describe("client instruction activation", () => {
  it("pins the deterministic source byte size and checksum", async () => { const bytes = buildSyntheticClientInstructionPdf(), hash = await crypto.subtle.digest("SHA-256", bytes); expect(bytes.byteLength).toBe(SYNTHETIC_CLIENT_INSTRUCTION_BYTE_SIZE); expect(Buffer.from(hash).toString("hex")).toBe(SYNTHETIC_CLIENT_INSTRUCTION_SHA256); });
  it("requires two distinct authenticated reviewers", () => expect(() => decideClientInstruction({ context, current, reviews: [{ reviewType: "source_integrity", outcome: "approved", reviewerId: "reviewer-a", sourceSha256: current.sourceSha256 }], raw: { ...base, action: "review_source", expectedRevision: 2, reviewId: "review-2", reviewType: "instruction_scope", outcome: "approved", evidence: "Reviewer confirmed source scope and exact client applicability." } })).toThrow("distinct reviewers"));
  it("blocks activation without both checksum-matched review types", () => expect(() => decideClientInstruction({ context, current: { ...current, status: "ready_for_activation", revision: 3 }, reviews: [{ reviewType: "source_integrity", outcome: "approved", reviewerId: "reviewer-a", sourceSha256: current.sourceSha256 }], raw: { ...base, action: "activate_source", expectedRevision: 3, layerId: "layer-1", approval: "Partner approved the reviewed instruction for exact-version activation." } })).toThrow("incomplete"));
  it("activates synthetic policy without claiming verified client content", () => { const result = decideClientInstruction({ context, current: { ...current, status: "ready_for_activation", revision: 3 }, reviews: [{ reviewType: "source_integrity", outcome: "approved", reviewerId: "reviewer-a", sourceSha256: current.sourceSha256 }, { reviewType: "instruction_scope", outcome: "approved", reviewerId: "reviewer-b", sourceSha256: current.sourceSha256 }], raw: { ...base, action: "activate_source", expectedRevision: 3, layerId: "layer-1", approval: "Partner approved the reviewed instruction for exact-version activation." } }); expect(result.toStatus).toBe("synthetic_active"); expect(result.event.payload).toMatchObject({ verifiedClientInstructionActivated: false, syntheticInstructionActivated: true }); });
  it("rejects stale revisions and cross-tenant commands", () => { expect(() => decideClientInstruction({ context, current, raw: { ...base, action: "deactivate_source", expectedRevision: 1, reason: "Partner deactivated this source after a version change." } })).toThrow("changed"); expect(() => decideClientInstruction({ context, current, raw: { ...base, tenantId: "other", action: "deactivate_source", expectedRevision: 2, reason: "Partner deactivated this source after a version change." } })).toThrow("Access denied"); });
});
