import { decideScaleAudit, measureLocalPerformance, scaleAuditCommand, type ScaleAssessmentState } from "@/domain/platform/scale-audit";
import { persistScaleAudit, readScaleAssessment, readScaleEvent, scaleProjection } from "@/platform/scale-audit-persistence";
import { PILOT_TENANT_ID, pilotContext } from "@/platform/pilot-context";
import { enforceRateLimit, RateLimitError, rateLimitResponse } from "@/platform/rate-limit-persistence";
import { requestActor } from "@/platform/request-actor";
import { assertTrustedWriteOrigin, RequestSecurityError } from "@/platform/request-security";
import { AuthorizationError } from "@/platform/tenant-context";
const limitation = "Four local in-process synthetic algorithm budgets are measured against the master targets. Event availability and background-job acknowledgment remain not measured. This is not representative multi-user load, browser/network performance, production database planning, archive streaming proof, edge/WAF validation, or independent assurance; production readiness remains false.";
export async function GET(request: Request) { try { const actor = requestActor(request); if (!actor) return Response.json({ error: "Authentication required" }, { status: 401 }); const context = pilotContext(actor); if (!context.roles.includes("partner")) throw new AuthorizationError(); return Response.json({ ...(await scaleProjection(PILOT_TENANT_ID)), limitation }); } catch (error) { if (error instanceof AuthorizationError) return Response.json({ error: "Access denied" }, { status: 403 }); return Response.json({ error: "Scale evidence could not be read" }, { status: 500 }); } }
export async function POST(request: Request) { try { assertTrustedWriteOrigin(request); const actor = requestActor(request); if (!actor) return Response.json({ error: "Authentication required" }, { status: 401 }); await enforceRateLimit({ tenantId: PILOT_TENANT_ID, actorId: actor.userId, action: "scale.command", policy: { limit: 8, windowMs: 60000 } }); const context = pilotContext(actor), command = scaleAuditCommand.parse(await request.json()), prior = await readScaleEvent(command.tenantId, command.idempotencyKey); if (prior) return Response.json({ persistence: { replayed: true, eventId: prior.eventId }, ...(await scaleProjection(command.tenantId)), limitation }); const current = await readScaleAssessment(command.tenantId, command.assessmentId), measurements = command.action === "run_local_benchmark" ? measureLocalPerformance() : undefined, decision = decideScaleAudit({ context, raw: command, current: current as ScaleAssessmentState | null, measurements }), persistence = await persistScaleAudit({ ...decision, measurements, actor }); return Response.json({ event: decision.event, persistence, ...(await scaleProjection(command.tenantId)), limitation }); } catch (error) { if (error instanceof RateLimitError) return rateLimitResponse(error); if (error instanceof RequestSecurityError) return Response.json({ error: "Untrusted request origin" }, { status: 403 }); if (error instanceof AuthorizationError) return Response.json({ error: "Access denied" }, { status: 403 }); return Response.json({ error: error instanceof Error ? error.message : "Scale command failed" }, { status: 400 }); } }
