"use client";

import { DatabaseZap, GitBranch, LoaderCircle } from "lucide-react";
import { useState } from "react";
import { StatusPill } from "./status-pill";

type Graph = { matter: { matterNumber: string; caption: string }; claims: Array<{ id: string; claimNumber: string }>; injuries: Array<{ id: string; injuryType: string; dateFrom: string | Date; bodyParts: string[] }>; adjudicationCases: Array<{ id: string; adjNumber: string; districtOffice?: string | null }>; relationships: Array<{ id: string; relationshipType: string }>; sourceLinks: Array<{ id: string; sourceSystem: string; providerMode: string }> };
type Projection = { graph: Graph | null; limitation?: string; error?: string };

export function MatterGraph() {
  const [data, setData] = useState<Projection | null>(null), [pending, setPending] = useState(false), [message, setMessage] = useState<string | null>(null);
  async function load() { setPending(true); setMessage(null); try { const response = await fetch("/api/matters/golden/graph"), result = await response.json() as Projection; if (!response.ok) throw new Error(result.error ?? "Matter graph could not be loaded"); setData(result); } catch (error) { setMessage(error instanceof Error ? error.message : "Load failed"); } finally { setPending(false); } }
  async function materialize() { setPending(true); setMessage(null); try { const response = await fetch("/api/matters/golden/graph", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "materialize_graph", tenantId: "tenant-golden", matterId: "matter-golden-001", idempotencyKey: `matter-graph-${crypto.randomUUID()}` }) }), result = await response.json() as Projection; if (!response.ok) throw new Error(result.error ?? "Matter graph could not be materialized"); setData(result); setMessage("Separate Matter, Claim, Injury, and ADJ records were persisted with relationship provenance."); } catch (error) { setMessage(error instanceof Error ? error.message : "Materialization failed"); } finally { setPending(false); } }
  if (!data) return <section className="panel operator-load"><GitBranch size={22}/><div><h2>Native matter graph</h2><p>Inspect the durable Matter → Claim → Injury and ADJ → Injury graph.</p><button className="secondary-action" type="button" onClick={() => void load()} disabled={pending}>{pending ? <LoaderCircle className="spin" size={15}/> : <GitBranch size={15}/>}Load graph</button>{message && <p className="inline-message">{message}</p>}</div></section>;
  if (!data.graph) return <section className="panel operator-panel"><header><div><h2>Native matter graph</h2><p>{data.limitation}</p></div><StatusPill tone="warning">Not materialized</StatusPill></header><p>The workflow fixture exists, but the normalized graph has not yet been written to D1.</p><div className="operator-actions"><button className="primary-action" type="button" onClick={() => void materialize()} disabled={pending}><DatabaseZap size={15}/>Materialize controlled graph</button></div>{message && <p className="inline-message" role="status">{message}</p>}</section>;
  const graph = data.graph;
  return <section className="panel operator-panel matter-graph-panel"><header><div><h2>Native matter graph</h2><p>{data.limitation}</p></div><StatusPill tone="success">Persisted · non-flattened</StatusPill></header><div className="matter-graph-grid"><article><small>MATTER</small><strong>{graph.matter.matterNumber}</strong><span>{graph.matter.caption}</span></article><article><small>CLAIM</small><strong>{graph.claims[0]?.claimNumber}</strong><span>{graph.claims.length} separate claim record</span></article><article><small>INJURY</small><strong>{graph.injuries[0]?.injuryType}</strong><span>{graph.injuries[0]?.bodyParts.join(", ")}</span></article><article><small>WCAB CASE</small><strong>{graph.adjudicationCases[0]?.adjNumber}</strong><span>{graph.adjudicationCases[0]?.districtOffice}</span></article></div><p><GitBranch size={15}/> {graph.relationships.length} provenanced relationships · {graph.sourceLinks.length} source-record links</p>{message && <p className="inline-message" role="status">{message}</p>}</section>;
}
