"use client";
import { CalendarRange, FileStack, LoaderCircle, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { StatusPill } from "./status-pill";
type Series = { id: string; titlePattern: string; cadence: string; interval: number; dayOfMonth: number | null; status: "draft" | "active" | "cancelled"; revision: number; occurrenceLimit: number; materializedCount: number };
type Occurrence = { id: string; seriesId: string; reportInstanceId: string | null; sequence: number; nominalDueOn: string; effectiveDueOn: string | null; status: string; exceptionAction: string };
type Projection = { series: Series[]; occurrences: Occurrence[]; limitation: string; error?: string };
const SERIES_ID = "report-series-summit-monthly-001", base = { tenantId: "tenant-golden", matterId: "matter-golden-001", seriesId: SERIES_ID };
const sections = [
  { sectionCode: "matter_identity", title: "Matter identity", body: "Elena Rivera v. Northstar Logistics, claim SCS-CA-884103, ADJ18420931. Deterministic synthetic pilot data.", sourceRecordIds: ["matter-golden-001", "claim-golden-001", "adj-golden-001"] },
  { sectionCode: "current_posture", title: "Current posture", body: "The synthetic matter is active with an MSC preparation workflow and an explicit external-provider boundary.", sourceRecordIds: ["proceeding-msc-golden-001"] },
  { sectionCode: "medical_status", title: "Medical status", body: "The checksum-pinned synthetic QME source is preserved; no production OCR or AI conclusion is claimed.", sourceRecordIds: ["evidence-qme-golden-001"] },
  { sectionCode: "authority", title: "Authority", body: "The attorney-reviewed structured authority ledger is the controlling source for this synthetic report.", sourceRecordIds: ["authority-candidate-125k"] },
  { sectionCode: "upcoming_events", title: "Upcoming events", body: "The local docket includes an MSC, preparation dependency, reminders, and explicit conflict evidence.", sourceRecordIds: ["calendar-event-msc-001", "calendar-conflict-rivera-001"] },
  { sectionCode: "legal_spend", title: "Legal spend", body: "The synthetic invoice lifecycle supplies integer-cent billed, collected, and realization evidence.", sourceRecordIds: ["invoice-golden-001"] },
];
const displayDate = (value: string) => new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
export function ReportRecurrenceOperations() {
  const [data, setData] = useState<Projection | null>(null), [pending, setPending] = useState(false), [message, setMessage] = useState<string | null>(null);
  async function load() { setPending(true); try { const response = await fetch("/api/reports/recurrence"), next = await response.json() as Projection; if (!response.ok) throw new Error(next.error ?? "Recurring reports could not be loaded"); setData(next); } catch (error) { setMessage(error instanceof Error ? error.message : "Load failed"); } finally { setPending(false); } }
  async function act(action: "create_series" | "activate_series" | "set_exception" | "materialize_window" | "cancel_series") {
    const series = data?.series.find(item => item.id === SERIES_ID);
    const body = action === "create_series" ? { action, ...base, definitionId: "report-definition-summit-recurring-v1", definitionCode: "SUMMIT-RECURRING-STATUS", titlePattern: "Monthly status — Rivera — {due_date}", recipientAddresses: ["jennifer.smith@example.test"], sectionTemplates: sections, cadence: "monthly", interval: 1, dayOfMonth: 31, startsOn: "2026-09-30", endsOn: "2026-12-31", occurrenceLimit: 4, timezone: "America/Los_Angeles", sandboxAcknowledged: true, idempotencyKey: `report-recurrence-create-${crypto.randomUUID()}` }
      : action === "activate_series" ? { action, ...base, expectedRevision: series?.revision, approval: "Attorney approved the source-linked template, recipients, and bounded local schedule.", idempotencyKey: `report-recurrence-activate-${crypto.randomUUID()}` }
      : action === "set_exception" ? { action, ...base, expectedRevision: series?.revision, nominalDueOn: "2026-10-31", exceptionAction: "move", movedDueOn: "2026-11-02", reason: "Move the October report to incorporate the scheduled medical update.", idempotencyKey: `report-recurrence-exception-${crypto.randomUUID()}` }
      : action === "materialize_window" ? { action, ...base, expectedRevision: series?.revision, throughDate: "2026-12-31", idempotencyKey: `report-recurrence-materialize-${crypto.randomUUID()}` }
      : { action, ...base, expectedRevision: series?.revision, reason: "Attorney ended future report recurrence while preserving created drafts.", idempotencyKey: `report-recurrence-cancel-${crypto.randomUUID()}` };
    setPending(true); try { const response = await fetch("/api/reports/recurrence", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), next = await response.json() as Projection; if (!response.ok) throw new Error(next.error ?? "Recurring report operation failed"); setData(next); setMessage("Recurring-report decision and event evidence recorded."); } catch (error) { setMessage(error instanceof Error ? error.message : "Operation failed"); } finally { setPending(false); }
  }
  if (!data) return <section className="panel operator-load"><FileStack size={22}/><div><h2>Governed report recurrence</h2><p>Create source-linked report drafts from an attorney-approved bounded schedule.</p><button className="secondary-action" onClick={() => void load()} disabled={pending}>{pending ? <LoaderCircle className="spin" size={15}/> : <FileStack size={15}/>}Load report schedule</button>{message && <p className="inline-message">{message}</p>}</div></section>;
  const series = data.series.find(item => item.id === SERIES_ID), occurrences = data.occurrences.filter(item => item.seriesId === SERIES_ID);
  const next = !series ? "create_series" : series.status === "draft" ? "activate_series" : series.status === "active" && !occurrences.length && series.revision === 2 ? "set_exception" : series.status === "active" && !occurrences.length ? "materialize_window" : series.status === "active" ? "cancel_series" : null;
  const labels = { create_series: "Create draft schedule", activate_series: "Approve report schedule", set_exception: "Move October report", materialize_window: "Create bounded report drafts", cancel_series: "Cancel future reports" } as const;
  return <section className="panel operator-panel"><header><div><h2>Governed report recurrence</h2><p>Monthly source-linked status drafts · maximum four · local schedule only</p></div><StatusPill tone={series?.status === "active" ? "success" : series?.status === "cancelled" ? "neutral" : "warning"}>{series?.status ?? "not created"}</StatusPill></header>{series && <p><strong>{series.titlePattern}</strong> · day {series.dayOfMonth} · revision {series.revision} · {series.materializedCount}/{series.occurrenceLimit} governed</p>}{occurrences.length > 0 && <div className="evidence-list">{occurrences.map(item => <p key={item.id}><ShieldCheck size={14}/><strong>#{item.sequence}</strong> {displayDate(item.nominalDueOn)}{item.exceptionAction === "move" && item.effectiveDueOn ? ` → ${displayDate(item.effectiveDueOn)}` : ""} · {item.reportInstanceId ? "draft created" : "skipped"}</p>)}</div>}{next && <div className="operator-actions"><button className="primary-action" onClick={() => void act(next)} disabled={pending}>{pending ? <LoaderCircle className="spin" size={15}/> : <CalendarRange size={15}/>} {labels[next]}</button></div>}<p className="operator-note">{data.limitation}</p>{message && <p className="inline-message" role="status">{message}</p>}</section>;
}
