"use client";
import { Activity, CheckCircle2, LoaderCircle } from "lucide-react";
import { useState } from "react";
import { StatusPill } from "./status-pill";
type Projection = { assessments: Array<{ id: string; status: string; overallOutcome: string; revision: number; workloadProfile: string; blockingGaps: string[]; maxPageSize: number; outboxBatchLimit: number; archiveByteLimit: number; archiveRowLimit: number }>; measurements: Array<{ id: string; assessmentId: string; metricCode: string; targetMs: number; measuredMs: number | null; status: string; method: string; limitation: string | null }>; decisions: Array<{ id: string; assessmentId: string; action: string }>; limitation?: string; error?: string };
const ID = "scale-assessment-local-001";
export function ScaleOperations() {
  const [data, setData] = useState<Projection | null>(null), [pending, setPending] = useState(false), [message, setMessage] = useState<string | null>(null);
  async function request(body?: Record<string, unknown>) { const response = await fetch("/api/admin/scale", { method: body ? "POST" : "GET", headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json() as Projection; if (!response.ok) throw new Error(payload.error ?? "Operation failed"); setData(payload); }
  async function load() { setPending(true); try { await request(); } catch (error) { setMessage(error instanceof Error ? error.message : "Load failed"); } finally { setPending(false); } }
  async function advance() { const assessment = data?.assessments.find((item) => item.id === ID), body = assessment ? { action: "review_capacity", tenantId: "tenant-golden", assessmentId: ID, expectedRevision: assessment.revision, outcome: "accept_with_gaps", reason: "Partner accepts this only as bounded local engineering evidence; every listed production and independent-validation gap remains blocking.", idempotencyKey: `scale-review-${crypto.randomUUID()}` } : { action: "run_local_benchmark", tenantId: "tenant-golden", assessmentId: ID, workloadProfile: "Twenty-five thousand synthetic matter rows in one local Worker process; 40 p95 samples per measured algorithm.", maxPageSize: 100, outboxBatchLimit: 100, archiveByteLimit: 67108864, archiveRowLimit: 50000, idempotencyKey: `scale-run-${crypto.randomUUID()}`, syntheticAcknowledged: true }; setPending(true); try { await request(body); setMessage(assessment ? "Conditional partner review recorded; production readiness remains false." : "Bounded local benchmark evidence recorded."); } catch (error) { setMessage(error instanceof Error ? error.message : "Operation failed"); } finally { setPending(false); } }
  if (!data) return <section className="panel operator-load"><Activity size={22}/><div><h2>Scale and performance evidence</h2><p>Load local budgets, workload ceilings, blocking gaps, and review evidence.</p><button className="secondary-action" onClick={() => void load()} disabled={pending}>{pending ? <LoaderCircle className="spin" size={15}/> : <Activity size={15}/>}Load scale audit</button>{message && <p className="inline-message">{message}</p>}</div></section>;
  const assessment = data.assessments.find((item) => item.id === ID), measurements = data.measurements.filter((item) => item.assessmentId === ID);
  return <section className="panel operator-panel"><header><div><h2>Scale and performance evidence</h2><p>{data.limitation}</p></div><StatusPill tone={assessment?.status === "rejected" ? "danger" : assessment?.status === "reviewed_with_gaps" ? "warning" : "info"}>{assessment?.status ?? "not measured"}</StatusPill></header>
    {assessment && <><dl><div><dt>Page</dt><dd>{assessment.maxPageSize}</dd></div><div><dt>Outbox batch</dt><dd>{assessment.outboxBatchLimit}</dd></div><div><dt>Archive</dt><dd>{Math.round(assessment.archiveByteLimit / 1048576)}MB</dd></div><div><dt>Rows</dt><dd>{assessment.archiveRowLimit / 1000}k</dd></div></dl><ol>{measurements.map((metric) => <li key={metric.id}><strong>{metric.metricCode} · {metric.status}</strong><small>target {metric.targetMs}ms · measured {metric.measuredMs === null ? "not measured" : `${metric.measuredMs}ms`} · {metric.method}</small></li>)}</ol><p><strong>Blocking gaps:</strong> {assessment.blockingGaps.join(" · ")}</p></>}
    {assessment?.status !== "reviewed_with_gaps" && assessment?.status !== "rejected" && <button className="primary-action" onClick={() => void advance()} disabled={pending}>{pending ? <LoaderCircle className="spin" size={15}/> : <CheckCircle2 size={15}/>} {assessment ? "Record conditional review" : "Run local benchmark"}</button>}{message && <p className="inline-message" role="status">{message}</p>}
  </section>;
}
