"use client";
import { CheckCircle2, LoaderCircle, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { StatusPill } from "./status-pill";
type Projection = { requests: Array<{ id: string; requestedAmountCents: number; settlementStructure: string; scope: string; examinerName: string; status: string; providerMode: string; revision: number; responseId: string | null; ledgerId: string | null }>; responses: Array<{ id: string; requestId: string; outcome: string; amountCents: number | null; settlementStructure: string | null; scope: string | null; negotiationThresholdCents: number | null; responderName: string }>; decisions: Array<{ id: string; requestId: string; action: string }>; current: { id: string; amountCents: number; status: string; grantorName: string } | null; limitation?: string; error?: string };
const REQUEST = "structured-authority-rivera-001", shared = { tenantId: "tenant-golden", matterId: "matter-golden-001", requestId: REQUEST };
export function StructuredAuthorityOperations() {
  const [data, setData] = useState<Projection | null>(null), [pending, setPending] = useState(false), [message, setMessage] = useState<string | null>(null);
  async function request(body?: Record<string, unknown>) { const response = await fetch("/api/authority/structured", { method: body ? "POST" : "GET", headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json() as Projection; if (!response.ok) throw new Error(payload.error ?? "Operation failed"); setData(payload); }
  async function load() { setPending(true); try { await request(); } catch (error) { setMessage(error instanceof Error ? error.message : "Load failed"); } finally { setPending(false); } }
  async function advance() {
    const item = data?.requests.find((request) => request.id === REQUEST), idempotencyKey = `structured-authority-${crypto.randomUUID()}`; let body: Record<string, unknown>;
    if (!item) body = { action: "create_request", ...shared, idempotencyKey, requestedAmountCents: 10000000, currency: "USD", settlementStructure: "C&R", scope: "Resolve all claims by C&R at the MSC", includes: ["permanent disability", "future medical", "attorney fees"], excludes: ["liens"], conditions: ["Call before exceeding $80,000"], examinerName: "Jennifer Smith", examinerEmail: "jennifer.smith@example.test", examinerOrganization: "Summit Claims Services", requestedExpiresAt: "2026-09-30T23:59:00.000Z", sandboxAcknowledged: true };
    else { const base = { ...shared, idempotencyKey, expectedRevision: item.revision };
      if (item.status === "draft") body = { action: "approve_request", ...base, reason: "Attorney reviewed the requested amount, structure, scope, inclusions, exclusions, conditions, examiner, and expiry." };
      else if (item.status === "approved_for_delivery") body = { action: "attempt_delivery", ...base, reason: "Record the honest secure approval page and delivery block without sending an invitation." };
      else if (item.status === "delivery_blocked") body = { action: "record_human_response", ...base, responseId: "structured-authority-response-rivera-001", outcome: "modified", amountCents: 9000000, currency: "USD", settlementStructure: "C&R", scope: "Resolve all claims by C&R at the MSC", includes: ["permanent disability", "future medical", "attorney fees"], excludes: ["liens"], conditions: ["Call before exceeding $75,000"], negotiationThresholdCents: 7500000, responderName: "Jennifer Smith", responderRole: "Claims examiner", responderOrganization: "Summit Claims Services", effectiveAt: "2026-08-20T17:00:00.000Z", expiresAt: "2026-09-30T23:59:00.000Z", evidence: "Attorney verified the explicitly synthetic modified response outside the disconnected approval page; no external signature or login is claimed." };
      else body = { action: "confirm_response", ...base, responseId: "structured-authority-response-rivera-001", candidateId: "structured-authority-candidate-rivera-001", ledgerId: "structured-authority-ledger-rivera-001", expirationTaskId: "structured-authority-expiration-task-rivera-001", reason: "Attorney verified the responder, source evidence, amount, scope, structure, inclusions, exclusions, threshold, effective date, and expiry." };
    }
    setPending(true); try { await request(body); setMessage("Structured authority evidence advanced."); } catch (error) { setMessage(error instanceof Error ? error.message : "Operation failed"); } finally { setPending(false); }
  }
  if (!data) return <section className="panel operator-load"><ShieldAlert size={22}/><div><h2>Structured client authority approval</h2><p>Load request, approval, delivery truth, response, ledger, and follow-up evidence.</p><button className="secondary-action" onClick={() => void load()} disabled={pending}>{pending ? <LoaderCircle className="spin" size={15}/> : <ShieldAlert size={15}/>}Load structured approval</button>{message && <p className="inline-message">{message}</p>}</div></section>;
  const item = data.requests.find((request) => request.id === REQUEST), response = data.responses.find((response) => response.requestId === REQUEST);
  return <section className="panel operator-panel"><header><div><h2>Structured authority approval lifecycle</h2><p>{data.limitation}</p></div><StatusPill tone={item?.status === "confirmed" ? "success" : item?.status === "delivery_blocked" ? "warning" : "info"}>{item?.status ?? "not requested"}</StatusPill></header>
    {item && <p><strong>Requested ${(item.requestedAmountCents / 100).toLocaleString("en-US", { style: "currency", currency: "USD" })}</strong> · {item.settlementStructure} · {item.examinerName} · revision {item.revision}</p>}
    {response && <p><strong>{response.outcome} response:</strong> {response.amountCents ? (response.amountCents / 100).toLocaleString("en-US", { style: "currency", currency: "USD" }) : "declined"} · threshold {response.negotiationThresholdCents ? (response.negotiationThresholdCents / 100).toLocaleString("en-US", { style: "currency", currency: "USD" }) : "—"}</p>}
    {item?.status === "delivery_blocked" && <div className="truth-banner"><ShieldAlert size={17}/><div><strong>No secure approval page or invitation exists</strong><p>The provider handoff stopped before delivery.</p></div></div>}
    {item?.status !== "confirmed" && item?.status !== "declined" && <button className="primary-action" onClick={() => void advance()} disabled={pending}>{pending ? <LoaderCircle className="spin" size={15}/> : <CheckCircle2 size={15}/>}Advance synthetic lifecycle</button>}{message && <p className="inline-message" role="status">{message}</p>}
  </section>;
}
