import { z } from "zod";
import { createEvent } from "@/platform/events";
import { authorizeMatter, requireRole, type TenantContext } from "@/platform/tenant-context";
const base={tenantId:z.string().min(1),matterId:z.string().min(1),recordRequestId:z.string().min(3).max(120),idempotencyKey:z.string().min(8).max(200)},revision=z.number().int().positive(),evidence=z.string().trim().min(12).max(1500),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const recordRequestCommand=z.discriminatedUnion("action",[
 z.object({action:z.literal("create"),...base,requestType:z.enum(["authorization","subpoena","informal_request"]),custodianName:z.string().trim().min(3).max(240),scope:z.string().trim().min(12).max(1500)}),
 z.object({action:z.literal("prepare"),...base,expectedRevision:revision,authorityBasis:evidence}),
 z.object({action:z.literal("record_service"),...base,expectedRevision:revision,serviceMethod:z.string().trim().min(3).max(100),servedDate:date,complianceDueDate:date,serviceEvidence:evidence}),
 z.object({action:z.literal("receive_records"),...base,expectedRevision:revision,receivedDate:date,documentCount:z.number().int().positive().max(100000),evidence}),
 z.object({action:z.literal("mark_deficiency"),...base,expectedRevision:revision,reason:evidence}),
 z.object({action:z.literal("resolve_deficiency"),...base,expectedRevision:revision,receivedDate:date,documentCount:z.number().int().positive().max(100000),evidence}),
 z.object({action:z.literal("complete_review"),...base,expectedRevision:revision,completenessEvidence:evidence}),
 z.object({action:z.literal("record_delivery"),...base,expectedRevision:revision,deliveredTo:z.string().trim().min(3).max(240),deliveryEvidence:evidence}),
 z.object({action:z.literal("close"),...base,expectedRevision:revision,costCents:z.number().int().nonnegative().max(100_000_000),billingDisposition:z.enum(["client_cost","firm_cost","waived","pending_review"]),evidence}),
 z.object({action:z.literal("cancel"),...base,expectedRevision:revision,reason:evidence}),
]);
export type RecordRequestCommand=z.infer<typeof recordRequestCommand>;export type RecordRequestState={id:string;status:"identified"|"prepared"|"served"|"received"|"deficient"|"reviewed"|"delivered"|"closed"|"cancelled";revision:number};
const expectedFrom={prepare:"identified",record_service:"prepared",receive_records:"served",mark_deficiency:"received",resolve_deficiency:"deficient",complete_review:"received",record_delivery:"reviewed",close:"delivered"}as const;const to={prepare:"prepared",record_service:"served",receive_records:"received",mark_deficiency:"deficient",resolve_deficiency:"received",complete_review:"reviewed",record_delivery:"delivered",close:"closed",cancel:"cancelled"}as const;
export function decideRecordRequest(input:{context:TenantContext;raw:unknown;current?:RecordRequestState|null}){const command=recordRequestCommand.parse(input.raw);authorizeMatter(input.context,command.tenantId,command.matterId);requireRole(input.context,["attorney","partner","paralegal","legal_assistant","records_specialist"]);let fromStatus="not_created",toStatus:RecordRequestState["status"]="identified";if(command.action!=="create"){const current=input.current;if(!current||current.id!==command.recordRequestId)throw new Error("Record request does not exist in this matter scope");if(current.revision!==command.expectedRevision)throw new Error("Record request changed; refresh before retrying");if(["closed","cancelled"].includes(current.status))throw new Error("Record request is terminal");fromStatus=current.status;if(command.action!=="cancel"&&current.status!==expectedFrom[command.action])throw new Error(`${command.action} is not allowed from ${current.status}`);toStatus=to[command.action];if(command.action==="record_service"&&command.complianceDueDate<command.servedDate)throw new Error("Compliance due date cannot precede service");}const suffix={create:"created",prepare:"prepared",record_service:"served",receive_records:"received",mark_deficiency:"deficiency_recorded",resolve_deficiency:"deficiency_resolved",complete_review:"review_completed",record_delivery:"delivery_recorded",close:"closed",cancel:"cancelled"}[command.action];return{command,fromStatus,toStatus,event:createEvent({eventType:`records.${suffix}`,tenantId:command.tenantId,aggregateType:"record_request",aggregateId:command.recordRequestId,matterId:command.matterId,actorId:input.context.userId,correlationId:command.idempotencyKey,idempotencyKey:command.idempotencyKey,source:"athena.web",visibility:"restricted",retentionPolicy:"matter-lifecycle-plus-firm-retention",payload:{action:command.action,fromStatus,toStatus,humanAuthorized:true,externalProviderOperation:false}})}}
