import { describe, expect, it } from "vitest";
import { decideTelephony, type TelephonyState } from "./lifecycle";
import { AuthorizationError, type TenantContext } from "@/platform/tenant-context";
const context: TenantContext = { tenantId: "t", userId: "attorney-1", roles: ["attorney"], matterAccess: new Set(["matter-1"]) }, base = { tenantId: "t", matterId: "matter-1", contactId: "contact-1", idempotencyKey: "telephony-test-001" };
const state = (status: TelephonyState["status"], revision = 1, patch: Partial<TelephonyState> = {}): TelephonyState => ({ id: "contact-1", status, revision, smsConsentStatus: "opted_in", voiceConsentStatus: "consented", recordingAllowed: false, ...patch });
describe("telephony lifecycle", () => {
  it("requires current opt-in before an SMS draft", () => expect(() => decideTelephony({ context, current: state("consented", 1, { smsConsentStatus: "opted_out" }), raw: { action: "draft_sms", ...base, expectedRevision: 1, interactionId: "sms-1", body: "Synthetic scheduling message with no confidential matter detail." } })).toThrow(/opt-in/));
  it("blocks delivery without claiming a provider attempt", () => { const x = decideTelephony({ context, current: state("sms_approved"), raw: { action: "attempt_sms_delivery", ...base, expectedRevision: 1, interactionId: "sms-1", reason: "Telephony provider credentials and delivery reconciliation are unavailable." } }); expect(x.toStatus).toBe("delivery_blocked"); expect(x.event.payload).toMatchObject({ providerConnected: false, deliveryAttempted: false }); });
  it("preserves STOP suppression and prohibits recording", () => { const stop = decideTelephony({ context, current: state("delivery_blocked"), raw: { action: "record_stop", ...base, expectedRevision: 1, stopInteractionId: "stop-1", receivedAt: "2026-08-20T12:00:00.000Z", evidence: "Human recorded an explicitly synthetic inbound STOP instruction." } }); expect(stop.event.payload).toMatchObject({ smsSuppressed: true }); expect(() => decideTelephony({ context, current: state("opted_out"), raw: { action: "record_call_metadata", ...base, expectedRevision: 1, callInteractionId: "call-1", occurredAt: "2026-08-20T12:05:00.000Z", durationSeconds: 300, evidence: "Human verified synthetic call metadata and consent evidence.", recordingCreated: true } })).toThrow(); });
  it("enforces order, attorney role, tenant, and matter", () => {
    expect(() => decideTelephony({ context: { ...context, roles: ["paralegal"] }, current: state("sms_draft"), raw: { action: "approve_sms", ...base, expectedRevision: 1, interactionId: "sms-1", reason: "Staff cannot approve substantive outbound text content." } })).toThrow(AuthorizationError);
    expect(() => decideTelephony({ context, current: state("sms_approved"), raw: { action: "attempt_sms_delivery", ...base, tenantId: "other", expectedRevision: 1, interactionId: "sms-1", reason: "Foreign tenant messaging must be rejected before delivery." } })).toThrow(AuthorizationError);
    expect(() => decideTelephony({ context, current: state("sms_approved"), raw: { action: "attempt_sms_delivery", ...base, matterId: "other", expectedRevision: 1, interactionId: "sms-1", reason: "Foreign matter messaging must be rejected before delivery." } })).toThrow(AuthorizationError);
  });
});
