import { describe, expect, it } from "vitest";
import { decideReport, validateReport, type ReportDefinitionState, type ReportState } from "./lifecycle";
const context = { tenantId: "t", userId: "u", roles: ["attorney"], matterAccess: new Set(["m"]) };
const codes = ["matter_identity", "current_posture", "medical_status", "authority", "upcoming_events", "legal_spend"];
const definition: ReportDefinitionState = { id: "def-1", code: "SUMMIT-90-DAY", version: 1, requiredSections: codes, contentStatus: "synthetic_sandbox" };
const report: ReportState = { id: "report-1", status: "draft", revision: 1, recipientAddresses: ["examiner@example.test"], unresolvedConflictCount: 0, sections: codes.map((sectionCode, index) => ({ sectionCode, position: index + 1, sourceRecordIds: [`source-${index}`] })) };
describe("governed reporting lifecycle", () => {
  it("passes only complete ordered source-linked reports", () => expect(validateReport(definition, report)).toMatchObject({ outcome: "pass", sourceCoverageCount: 6 }));
  it("fails missing sources and unresolved conflicts", () => { expect(validateReport(definition, { ...report, sections: report.sections.map((item, index) => index ? item : { ...item, sourceRecordIds: [] }) }).outcome).toBe("fail"); expect(validateReport(definition, { ...report, unresolvedConflictCount: 1 }).outcome).toBe("fail"); });
  it("requires validation before attorney approval", () => expect(() => decideReport({ context, report, raw: { action: "approve_report", tenantId: "t", matterId: "m", reportInstanceId: "report-1", expectedRevision: 1, reason: "Attorney reviewed every cited report section.", idempotencyKey: "report-approve" } })).toThrow("validated"));
  it("blocks delivery without claiming a provider attempt", () => { const result = decideReport({ context, report: { ...report, status: "approved", revision: 3 }, raw: { action: "record_delivery_block", tenantId: "t", matterId: "m", reportInstanceId: "report-1", expectedRevision: 3, deliveryId: "delivery-1", reason: "Microsoft delivery credentials and reconciliation remain unavailable.", idempotencyKey: "report-block" } }); expect(result.toStatus).toBe("delivery_blocked"); expect(result.event.payload).toMatchObject({ microsoftConnected: false, providerDeliveryAttempted: false }); });
  it("enforces optimistic revision and tenant isolation", () => { expect(() => decideReport({ context, report, definition, validation: validateReport(definition, report), raw: { action: "validate_report", tenantId: "t", matterId: "m", reportInstanceId: "report-1", expectedRevision: 2, idempotencyKey: "report-stale" } })).toThrow("changed"); expect(() => decideReport({ context, raw: { action: "validate_report", tenantId: "other", matterId: "m", reportInstanceId: "report-1", expectedRevision: 1, idempotencyKey: "report-tenant" } })).toThrow("Access denied"); });
});
