import{z}from"zod";import{createEvent}from"@/platform/events";import{authorizeMatter,requireRole,type TenantContext}from"@/platform/tenant-context";
const base={tenantId:z.string().min(1),matterId:z.string().min(1),idempotencyKey:z.string().min(8).max(200)},money=z.number().int().nonnegative().max(1_000_000_000),evidence=z.string().trim().min(12).max(1500),revision=z.number().int().positive();
export const billingLifecycleCommand=z.discriminatedUnion("action",[
 z.object({action:z.literal("setup_profile"),...base,profileId:z.string().min(3),clientId:z.string().min(3),hourlyRateCents:money.positive(),billingIncrementMinutes:z.number().int().min(1).max(60),approvedTimekeeperIds:z.array(z.string().min(3)).min(1),allowedTaskCodes:z.array(z.string().min(1)).min(1),allowedActivityCodes:z.array(z.string().min(1)).min(1),allowedExpenseCodes:z.array(z.string().min(1)).min(1),effectiveAt:z.iso.datetime(),sandboxAcknowledged:z.literal(true)}),
 z.object({action:z.literal("record_expense"),...base,expenseId:z.string().min(3),expenseCode:z.string().min(1),description:z.string().min(8),amountCents:money.positive(),incurredAt:z.iso.datetime(),sourceType:z.string().min(3),sourceId:z.string().min(3)}),
 z.object({action:z.literal("generate_prebill"),...base,prebillId:z.string().min(3),profileId:z.string().min(3),timeEntryId:z.string().min(3),expenseId:z.string().min(3),periodStart:z.iso.datetime(),periodEnd:z.iso.datetime()}),
 z.object({action:z.literal("approve_prebill"),...base,prebillId:z.string().min(3),expectedRevision:revision,reason:evidence}),
 z.object({action:z.literal("generate_invoice"),...base,prebillId:z.string().min(3),invoiceId:z.string().min(3),invoiceNumber:z.string().min(3),clientMatterId:z.string().min(3)}),
 z.object({action:z.literal("validate_ledes"),...base,invoiceId:z.string().min(3),expectedRevision:revision,ledesId:z.string().min(3)}),
 z.object({action:z.literal("record_submission"),...base,invoiceId:z.string().min(3),expectedRevision:revision,evidence,externalReference:z.string().min(3),providerMode:z.literal("human_verified_external")}),
 z.object({action:z.literal("record_rejection"),...base,invoiceId:z.string().min(3),expectedRevision:revision,amountCents:money.positive(),reasonCode:z.string().min(2),evidence,externalReference:z.string().min(3),providerMode:z.literal("human_verified_external")}),
 z.object({action:z.literal("open_appeal"),...base,invoiceId:z.string().min(3),expectedRevision:revision,amountCents:money.positive(),reasonCode:z.string().min(2),evidence}),
 z.object({action:z.literal("resolve_appeal"),...base,invoiceId:z.string().min(3),expectedRevision:revision,recoveredAmountCents:money,reasonCode:z.string().min(2),evidence,externalReference:z.string().min(3),providerMode:z.literal("human_verified_external")}),
 z.object({action:z.literal("record_payment"),...base,invoiceId:z.string().min(3),expectedRevision:revision,paymentId:z.string().min(3),amountCents:money.positive(),paidAt:z.iso.datetime(),externalReference:z.string().min(3),providerMode:z.literal("human_verified_external")}),
]);export type BillingLifecycleCommand=z.infer<typeof billingLifecycleCommand>;
export type BillingProfile={hourlyRateCents:number;billingIncrementMinutes:number;approvedTimekeeperIds:string[];allowedTaskCodes:string[];allowedActivityCodes:string[];allowedExpenseCodes:string[];effectiveAt:Date;expiresAt?:Date|null};export type BillableTime={id:string;minutes:number;timekeeperId:string;taskCode:string;activityCode:string;narrative:string;status:string};export type BillableExpense={id:string;expenseCode:string;amountCents:number;description:string;status:string};
export function calculatePrebill(input:{profile:BillingProfile;time:BillableTime;expense:BillableExpense;asOf:Date}){const{profile,time,expense,asOf}=input,hardStops:string[]=[];if(time.status!=="confirmed")hardStops.push("Time entry is not human-confirmed.");if(!profile.approvedTimekeeperIds.includes(time.timekeeperId))hardStops.push("Timekeeper is not approved.");if(!profile.allowedTaskCodes.includes(time.taskCode))hardStops.push("Task code is not allowed.");if(!profile.allowedActivityCodes.includes(time.activityCode))hardStops.push("Activity code is not allowed.");if(!profile.allowedExpenseCodes.includes(expense.expenseCode))hardStops.push("Expense code is not allowed.");if(profile.effectiveAt>asOf||profile.expiresAt&&profile.expiresAt<asOf)hardStops.push("Billing profile is not effective.");const roundedMinutes=Math.ceil(time.minutes/profile.billingIncrementMinutes)*profile.billingIncrementMinutes,timeAmountCents=Math.round(roundedMinutes*profile.hourlyRateCents/60),expenseAmountCents=expense.amountCents,totalCents=timeAmountCents+expenseAmountCents;return{outcome:hardStops.length?"hard_stop"as const:"pass"as const,hardStops,roundedMinutes,timeAmountCents,expenseAmountCents,totalCents,adjustmentAmountCents:0};}
export type InvoiceState={id:string;status:"draft"|"validated"|"submitted_manual"|"rejected"|"appealed"|"partially_paid"|"paid"|"written_off";revision:number;invoiceNumber:string;clientMatterId:string;grossAmountCents:number;reductionAmountCents:number;appealRecoveryCents:number;paidAmountCents:number;balanceCents:number;lineCount:number;lineAmountCents:number};
export function validateLedes(invoice:InvoiceState){const checks=[{code:"invoice_number",status:invoice.invoiceNumber?"pass":"fail",explanation:"Invoice number is required."},{code:"client_matter_id",status:invoice.clientMatterId?"pass":"fail",explanation:"Client matter ID is required."},{code:"line_count",status:invoice.lineCount>0?"pass":"fail",explanation:"At least one billable line is required."},{code:"amount_reconciliation",status:invoice.lineAmountCents===invoice.grossAmountCents?"pass":"fail",explanation:"Line amounts must reconcile to invoice gross."}]as const;return{outcome:checks.some(x=>x.status==="fail")?"fail"as const:"pass"as const,checks,format:"LEDES1998B"as const,providerMode:"not_connected"as const};}
export function decideBillingLifecycle(input:{context:TenantContext;raw:unknown;profileExists?:boolean;expenseExists?:boolean;prebill?:{status:string;revision:number}|null;invoice?:InvoiceState|null;prebillCalculation?:ReturnType<typeof calculatePrebill>;ledesValidation?:ReturnType<typeof validateLedes>}){const command=billingLifecycleCommand.parse(input.raw);authorizeMatter(input.context,command.tenantId,command.matterId);requireRole(input.context,["attorney","partner","billing_specialist"]);let aggregateType="billing",fromStatus="not_created",toStatus="recorded";const aggregateId="profileId"in command?command.profileId:"expenseId"in command?command.expenseId:"prebillId"in command?command.prebillId:command.invoiceId;
 if(command.action==="setup_profile"){if(input.profileExists)throw new Error("Billing profile already exists");toStatus="active";}else if(command.action==="record_expense"){if(input.expenseExists)throw new Error("Expense already exists");}
 else if(command.action==="generate_prebill"){aggregateType="prebill";if(!input.prebillCalculation||input.prebillCalculation.outcome!=="pass")throw new Error(input.prebillCalculation?.hardStops.join(" ")||"Prebill inputs are invalid");toStatus="draft";}
 else if(command.action==="approve_prebill"){aggregateType="prebill";if(!input.prebill||input.prebill.status!=="draft"||input.prebill.revision!==command.expectedRevision)throw new Error("Prebill is not an approvable current revision");fromStatus=input.prebill.status;toStatus="approved";}
 else if(command.action==="generate_invoice"){aggregateType="invoice";if(!input.prebill||input.prebill.status!=="approved")throw new Error("Only an approved prebill can create an invoice");toStatus="draft";}
 else{aggregateType="invoice";const invoice=input.invoice;if(!invoice||invoice.revision!==command.expectedRevision)throw new Error("Invoice is not a current revision");fromStatus=invoice.status;if(command.action==="validate_ledes"){if(invoice.status!=="draft"||input.ledesValidation?.outcome!=="pass")throw new Error("Invoice failed LEDES validation");toStatus="validated";}else if(command.action==="record_submission"){if(invoice.status!=="validated")throw new Error("Only a validated invoice can be submitted");toStatus="submitted_manual";}else if(command.action==="record_rejection"){if(invoice.status!=="submitted_manual"||command.amountCents>invoice.balanceCents)throw new Error("Rejection is not valid for this invoice");toStatus="rejected";}else if(command.action==="open_appeal"){if(invoice.status!=="rejected"||command.amountCents>invoice.reductionAmountCents)throw new Error("Appeal exceeds the recorded rejection");toStatus="appealed";}else if(command.action==="resolve_appeal"){if(invoice.status!=="appealed"||command.recoveredAmountCents>invoice.reductionAmountCents)throw new Error("Appeal recovery exceeds the recorded reduction");toStatus="rejected";}else{const collectible=invoice.grossAmountCents-invoice.reductionAmountCents+invoice.appealRecoveryCents;if(invoice.paidAmountCents+command.amountCents>collectible)throw new Error("Payment exceeds collectible balance");toStatus=invoice.paidAmountCents+command.amountCents===collectible?"paid":"partially_paid";}}
 const amount="amountCents"in command?command.amountCents:"recoveredAmountCents"in command?command.recoveredAmountCents:input.prebillCalculation?.totalCents??null;return{command,aggregateType,aggregateId,fromStatus,toStatus,event:createEvent({eventType:`billing.${command.action}`,tenantId:command.tenantId,aggregateType,aggregateId,matterId:command.matterId,actorId:input.context.userId,correlationId:command.idempotencyKey,idempotencyKey:command.idempotencyKey,source:"athena.web",visibility:"restricted",retentionPolicy:"matter-lifecycle-plus-firm-retention",payload:{action:command.action,fromStatus,toStatus,amountCents:amount,humanAuthorized:true,externalProviderConnected:false,providerMode:"providerMode"in command?command.providerMode:"athena_native"}})};}
