import { describe, expect, it } from "vitest";
import { budgetPlanningCommand, calculatePlanning, decideBudgetPlanning } from "./planning";
const context = { tenantId: "t", userId: "u", roles: ["attorney"], matterAccess: new Set(["m"]) }, budget = { id: "budget-1", status: "approved" as const, revision: 2, totalBudgetCents: 5_000_000 };
describe("billing planning", () => {
  it("reconciles integer-cent accrual, variance, realization, and contribution", () => expect(calculatePlanning({ totalBudgetCents: 5_000_000, feesCents: 1_250_000, expensesCents: 50_000, billedCents: 1_200_000, collectedCents: 1_000_000, workedValueCents: 1_250_000, directCostCents: 400_000 })).toEqual({ totalAccruedCents: 1_300_000, budgetVarianceCents: 3_700_000, realizationBasisPoints: 8000, contributionCents: 600_000 }));
  it("rejects phase totals that do not reconcile", () => expect(() => budgetPlanningCommand.parse({ action: "materialize_fixture_budget", tenantId: "t", matterId: "m", budgetId: "budget-1", title: "Matter budget", totalBudgetCents: 100, effectiveDate: "2026-08-20", phases: [{ id: "phase-1", phaseCode: "P1", title: "Phase one", budgetCents: 99 }, { id: "phase-2", phaseCode: "P2", title: "Phase two", budgetCents: 2 }], sandboxAcknowledged: true, idempotencyKey: "budget-create" })).toThrow("reconcile"));
  it("requires approval before financial snapshots", () => expect(() => decideBudgetPlanning({ context, budget: { ...budget, status: "draft" }, raw: { action: "record_accrual", tenantId: "t", matterId: "m", budgetId: "budget-1", expectedRevision: 2, accrualId: "accrual-1", period: "2026-08", feesCents: 100, expensesCents: 10, sourceRecordIds: ["time-1"], idempotencyKey: "budget-accrual" } })).toThrow("approved"));
  it("rejects collection above billed value", () => expect(() => budgetPlanningCommand.parse({ action: "snapshot_profitability", tenantId: "t", matterId: "m", budgetId: "budget-1", expectedRevision: 2, snapshotId: "profit-1", asOfDate: "2026-08-20", billedCents: 100, collectedCents: 101, workedValueCents: 120, directCostCents: 40, sourceRecordIds: ["invoice-1"], idempotencyKey: "budget-profit" })).toThrow("exceed"));
  it("enforces revision and tenant isolation", () => { expect(() => decideBudgetPlanning({ context, budget, raw: { action: "record_accrual", tenantId: "t", matterId: "m", budgetId: "budget-1", expectedRevision: 1, accrualId: "accrual-1", period: "2026-08", feesCents: 100, expensesCents: 10, sourceRecordIds: ["time-1"], idempotencyKey: "budget-stale" } })).toThrow("changed"); expect(() => decideBudgetPlanning({ context, raw: { action: "approve_budget", tenantId: "other", matterId: "m", budgetId: "budget-1", expectedRevision: 1, reason: "Attorney approved the budget sources.", idempotencyKey: "budget-tenant" } })).toThrow("Access denied"); });
});
