import { z } from "zod";
import { createEvent } from "@/platform/events";
import { authorizeMatter,requireRole,type TenantContext } from "@/platform/tenant-context";
const base={tenantId:z.string().min(1),matterId:z.string().min(1),packetId:z.string().min(3).max(120),idempotencyKey:z.string().min(8).max(200)},revision=z.number().int().positive(),evidence=z.string().trim().min(12).max(1500);
export const filingPacketCommand=z.discriminatedUnion("action",[
 z.object({action:z.literal("create"),...base,proceedingId:z.string().min(3).max(120),packetType:z.string().trim().min(3).max(120),adjNumber:z.string().trim().max(80).optional(),uan:z.string().trim().max(120).optional(),venue:z.string().trim().max(240).optional(),judge:z.string().trim().max(200).optional(),submissionIdentity:z.string().min(8).max(160),sandboxAcknowledged:z.literal(true)}),
 z.object({action:z.literal("add_document"),...base,expectedRevision:revision,documentId:z.string().min(3).max(120),kind:z.enum(["primary_form","cover_sheet","separator_sheet","proof_of_service","attachment"]),title:z.string().trim().min(3).max(240),position:z.number().int().positive().max(1000),sha256:z.string().regex(/^[a-f0-9]{64}$/),signatureStatus:z.enum(["present","missing","not_required"]),sourceDocumentId:z.string().min(3).max(160)}),
 z.object({action:z.literal("validate"),...base,expectedRevision:revision}),
 z.object({action:z.literal("approve"),...base,expectedRevision:revision,reason:evidence}),
 z.object({action:z.literal("handoff"),...base,expectedRevision:revision}),
 z.object({action:z.literal("record_status"),...base,expectedRevision:revision,outcome:z.enum(["accepted","rejected"]),evidence,externalReference:z.string().trim().min(3).max(240),providerMode:z.literal("human_verified_external")}),
 z.object({action:z.literal("correct"),...base,expectedRevision:revision,correctedPacketId:z.string().min(3).max(120),reason:evidence}),
]);
export type FilingPacketCommand=z.infer<typeof filingPacketCommand>;
export type FilingDocument={kind:"primary_form"|"cover_sheet"|"separator_sheet"|"proof_of_service"|"attachment";position:number;signatureStatus:"present"|"missing"|"not_required";sha256:string};
export type FilingPacketState={id:string;status:"draft"|"validation_failed"|"ready_for_approval"|"approved"|"handoff_blocked"|"handed_off"|"rejected"|"accepted"|"superseded";revision:number;revisionNumber:number;submissionIdentity:string;adjNumber?:string|null;uan?:string|null;venue?:string|null;formContentStatus:"synthetic_sandbox"|"pending_attorney_review"|"attorney_approved";requiredDocumentKinds:string[];documents:FilingDocument[]};
export function validateFilingPacket(packet:FilingPacketState){const docs=packet.documents,required=packet.requiredDocumentKinds,positions=[...docs].sort((a,b)=>a.position-b.position).map(x=>x.position),checks=[
 {code:"adj_number",status:packet.adjNumber?"pass":"fail",explanation:packet.adjNumber?"ADJ identifier is recorded.":"ADJ identifier is missing."},
 {code:"uan",status:packet.uan?"pass":"fail",explanation:packet.uan?"UAN is recorded.":"UAN is missing."},
 {code:"venue",status:packet.venue?"pass":"fail",explanation:packet.venue?"Venue is recorded.":"Venue is missing."},
 {code:"required_documents",status:required.every(kind=>docs.some(x=>x.kind===kind))?"pass":"fail",explanation:required.every(kind=>docs.some(x=>x.kind===kind))?"Every required packet document kind is present.":"One or more required packet document kinds are missing."},
 {code:"document_order",status:docs.length>0&&positions.every((x,i)=>x===i+1)?"pass":"fail",explanation:docs.length>0&&positions.every((x,i)=>x===i+1)?"Document positions are contiguous and deterministic.":"Document positions are not contiguous from one."},
 {code:"required_signatures",status:docs.filter(x=>x.kind==="primary_form"||x.kind==="proof_of_service").every(x=>x.signatureStatus==="present")&&required.filter(x=>x==="primary_form"||x==="proof_of_service").every(kind=>docs.some(x=>x.kind===kind&&x.signatureStatus==="present"))?"pass":"fail",explanation:"Primary form and proof-of-service signatures must be present."},
 {code:"checksums",status:docs.length>0&&docs.every(x=>/^[a-f0-9]{64}$/.test(x.sha256))?"pass":"fail",explanation:"Every packet document must retain a SHA-256 identity."},
 {code:"jurisdiction_content",status:packet.formContentStatus==="synthetic_sandbox"||packet.formContentStatus==="attorney_approved"?"pass":"fail",explanation:packet.formContentStatus==="synthetic_sandbox"?"Synthetic sandbox form definition is allowed only for this controlled pilot proof.":packet.formContentStatus==="attorney_approved"?"Form definition has attorney-approved content status.":"Form definition is pending attorney review."},
 ] as const;return{checks,outcome:checks.some(x=>x.status==="fail")?"fail" as const:"pass" as const,nonAutonomous:true,transmissionAttempted:false};}
export function decideFilingPacket(input:{context:TenantContext;raw:unknown;current?:FilingPacketState|null;evaluation?:ReturnType<typeof validateFilingPacket>;correctedExists?:boolean}){const command=filingPacketCommand.parse(input.raw);authorizeMatter(input.context,command.tenantId,command.matterId);requireRole(input.context,["attorney","partner","paralegal","legal_assistant","docketing"]);const current=input.current;let fromStatus="not_created",toStatus:FilingPacketState["status"]="draft";
 if(command.action==="create"){if(current)throw new Error("Filing packet already exists");}
 else{if(!current||current.id!==command.packetId)throw new Error("Filing packet does not exist in this matter scope");if(current.revision!==command.expectedRevision)throw new Error("Filing packet changed; refresh before retrying");fromStatus=current.status;
  if(command.action==="add_document"){if(!["draft","validation_failed"].includes(current.status))throw new Error("Documents can only be added before approval");toStatus="draft";}
  else if(command.action==="validate"){if(!["draft","validation_failed"].includes(current.status)||!input.evaluation)throw new Error("Packet cannot be validated from its current state");toStatus=input.evaluation.outcome==="pass"?"ready_for_approval":"validation_failed";}
  else if(command.action==="approve"){requireRole(input.context,["attorney","partner","docketing"]);if(current.status!=="ready_for_approval")throw new Error("Only a validated packet can be approved");toStatus="approved";}
  else if(command.action==="handoff"){if(current.status!=="approved")throw new Error("Only an approved packet can be handed off");toStatus="handoff_blocked";}
  else if(command.action==="record_status"){if(!["approved","handoff_blocked","handed_off"].includes(current.status))throw new Error("External status cannot be recorded from this state");toStatus=command.outcome;}
  else{if(current.status!=="rejected")throw new Error("Only a rejected packet can be corrected");if(input.correctedExists)throw new Error("Corrected packet identity already exists");if(command.correctedPacketId===command.packetId)throw new Error("Correction requires a new packet identity");toStatus="superseded";}
 }
 const suffix={create:"created",add_document:"document_added",validate:"validated",approve:"approved",handoff:"handoff_blocked",record_status:"status_recorded",correct:"corrected"}[command.action];return{command,fromStatus,toStatus,event:createEvent({eventType:`filing_packet.${suffix}`,tenantId:command.tenantId,aggregateType:"filing_packet",aggregateId:command.packetId,matterId:command.matterId,actorId:input.context.userId,correlationId:command.idempotencyKey,idempotencyKey:command.idempotencyKey,source:"athena.web",visibility:"restricted",retentionPolicy:"matter-lifecycle-plus-firm-retention",payload:{action:command.action,fromStatus,toStatus,correctedPacketId:command.action==="correct"?command.correctedPacketId:null,validationOutcome:input.evaluation?.outcome??null,humanAuthorized:true,eamsConnected:false,externalProviderOperation:false,nonAutonomous:true}})};}
