import { describe,expect,it } from "vitest";
import { decideFilingPacket,validateFilingPacket,type FilingPacketState } from "./packet";
const context={tenantId:"tenant-a",userId:"user-a",roles:["attorney" as const],matterAccess:new Set(["matter-a"])};
const hash="a".repeat(64),required=["primary_form","cover_sheet","separator_sheet","proof_of_service"];
function packet(status:FilingPacketState["status"]="draft"):FilingPacketState{return{id:"packet-1",status,revision:1,revisionNumber:1,submissionIdentity:"submission-1",adjNumber:"ADJ123",uan:"UAN123",venue:"WCAB Oakland",formContentStatus:"synthetic_sandbox",requiredDocumentKinds:required,documents:required.map((kind,i)=>({kind:kind as FilingPacketState["documents"][number]["kind"],position:i+1,signatureStatus:kind==="primary_form"||kind==="proof_of_service"?"present":"not_required",sha256:hash}))}}
describe("filing packet",()=>{
 it("fails validation with actionable missing data and packet parts",()=>{const x=packet();x.uan=null;x.documents=[];const result=validateFilingPacket(x);expect(result.outcome).toBe("fail");expect(result.checks.filter(y=>y.status==="fail").map(y=>y.code)).toEqual(expect.arrayContaining(["uan","required_documents","document_order","required_signatures","checksums"]))});
 it("passes a deterministic ordered signed packet without transmitting",()=>expect(validateFilingPacket(packet())).toMatchObject({outcome:"pass",nonAutonomous:true,transmissionAttempted:false}));
 it("requires validation before human approval and turns handoff into an honest disconnected block",()=>{expect(()=>decideFilingPacket({context,current:packet("draft"),raw:{action:"approve",tenantId:"tenant-a",matterId:"matter-a",packetId:"packet-1",expectedRevision:1,reason:"Attorney reviewed the complete packet.",idempotencyKey:"packet-approve"}})).toThrow("validated");const d=decideFilingPacket({context,current:packet("approved"),raw:{action:"handoff",tenantId:"tenant-a",matterId:"matter-a",packetId:"packet-1",expectedRevision:1,idempotencyKey:"packet-handoff"}});expect(d.toStatus).toBe("handoff_blocked");expect(d.event.payload).toMatchObject({eamsConnected:false,externalProviderOperation:false})});
 it("links a correction to a new identity and prevents duplicate correction identity",()=>{const current=packet("rejected");expect(decideFilingPacket({context,current,correctedExists:false,raw:{action:"correct",tenantId:"tenant-a",matterId:"matter-a",packetId:"packet-1",expectedRevision:1,correctedPacketId:"packet-2",reason:"Correct separator sheet ordering and preserve prior receipt history.",idempotencyKey:"packet-correct"}}).toStatus).toBe("superseded");expect(()=>decideFilingPacket({context,current,correctedExists:true,raw:{action:"correct",tenantId:"tenant-a",matterId:"matter-a",packetId:"packet-1",expectedRevision:1,correctedPacketId:"packet-2",reason:"Correct separator sheet ordering and preserve prior receipt history.",idempotencyKey:"packet-correct-2"}})).toThrow("already exists")});
 it("enforces tenant isolation and human-verified external status mode",()=>{expect(()=>decideFilingPacket({context,current:null,raw:{action:"create",tenantId:"tenant-b",matterId:"matter-a",packetId:"packet-1",proceedingId:"p-1",packetType:"msc",submissionIdentity:"submission-1",sandboxAcknowledged:true,idempotencyKey:"packet-create"}})).toThrow("Access denied");expect(()=>decideFilingPacket({context,current:packet("handoff_blocked"),raw:{action:"record_status",tenantId:"tenant-a",matterId:"matter-a",packetId:"packet-1",expectedRevision:1,outcome:"accepted",evidence:"Receipt manually inspected by authorized docketing staff.",externalReference:"receipt-1",providerMode:"approved_provider",idempotencyKey:"packet-status"}})).toThrow()});
});
