import { createId } from "@paralleldrive/cuid2";
import { and, asc, eq } from "drizzle-orm";
import { getDocumentBucket, getPreviewDb } from "../../db";
import { clientInstructionDecisions, clientInstructionReviews, clientInstructionSources, documentEvidenceRecords, governancePolicyLayers, optimisticWriteClaims, previewEvents, previewOutbox } from "../../db/schema";
import type { ClientInstructionCommand } from "@/domain/governance/client-instruction";
import { buildSyntheticClientInstructionPdf, SYNTHETIC_CLIENT_INSTRUCTION_BYTE_SIZE, SYNTHETIC_CLIENT_INSTRUCTION_SHA256 } from "@/domain/governance/synthetic-client-instruction";
import type { EventEnvelope } from "./events";
import { OptimisticConcurrencyError, rethrowOptimisticClaimConflict } from "./optimistic-concurrency";
import type { RequestActor } from "./request-actor";

export async function clientInstructionProjection(tenantId: string, matterId: string) { const db = getPreviewDb(); const [sources, reviews, decisions] = await Promise.all([db.select().from(clientInstructionSources).where(and(eq(clientInstructionSources.tenantId, tenantId), eq(clientInstructionSources.matterId, matterId))).orderBy(asc(clientInstructionSources.createdAt)), db.select().from(clientInstructionReviews).where(and(eq(clientInstructionReviews.tenantId, tenantId), eq(clientInstructionReviews.matterId, matterId))).orderBy(asc(clientInstructionReviews.createdAt)), db.select().from(clientInstructionDecisions).where(and(eq(clientInstructionDecisions.tenantId, tenantId), eq(clientInstructionDecisions.matterId, matterId))).orderBy(asc(clientInstructionDecisions.createdAt))]); return { sources, reviews, decisions }; }
export async function readClientInstruction(tenantId: string, matterId: string, instructionId: string) { const [row] = await getPreviewDb().select().from(clientInstructionSources).where(and(eq(clientInstructionSources.tenantId, tenantId), eq(clientInstructionSources.matterId, matterId), eq(clientInstructionSources.id, instructionId))).limit(1); return row ?? null; }
export async function listClientInstructionReviews(tenantId: string, matterId: string, instructionId: string) { return getPreviewDb().select().from(clientInstructionReviews).where(and(eq(clientInstructionReviews.tenantId, tenantId), eq(clientInstructionReviews.matterId, matterId), eq(clientInstructionReviews.instructionId, instructionId))).orderBy(asc(clientInstructionReviews.createdAt)); }
export async function readClientInstructionEvent(tenantId: string, idempotencyKey: string) { const [row] = await getPreviewDb().select({ eventId: previewEvents.eventId }).from(previewEvents).where(and(eq(previewEvents.tenantId, tenantId), eq(previewEvents.idempotencyKey, idempotencyKey))).limit(1); return row ?? null; }

export async function persistClientInstruction(input: { command: ClientInstructionCommand; fromStatus: string; toStatus: string; event: EventEnvelope<Record<string, unknown>>; actor: RequestActor }) {
  const db = getPreviewDb(), bucket = getDocumentBucket(), c = input.command, now = new Date(input.event.occurredAt), prior = await readClientInstructionEvent(c.tenantId, c.idempotencyKey); if (prior) return { replayed: true, eventId: prior.eventId };
  const eventWrite = db.insert(previewEvents).values({ eventId: input.event.eventId, eventType: input.event.eventType, eventVersion: input.event.eventVersion, tenantId: input.event.tenantId, aggregateType: input.event.aggregateType, aggregateId: input.event.aggregateId, matterId: input.event.matterId, actorId: input.actor.userId, occurredAt: now, correlationId: input.event.correlationId, causationId: input.event.causationId, idempotencyKey: input.event.idempotencyKey, source: input.event.source, visibility: input.event.visibility, retentionPolicy: input.event.retentionPolicy, payload: input.event.payload });
  const outboxWrite = db.insert(previewOutbox).values({ id: createId(), tenantId: c.tenantId, eventId: input.event.eventId, topic: "athena.client-instruction", payload: input.event, attempts: 0, availableAt: now });
  const reason = c.action === "materialize_synthetic_source" ? "Deterministic client-instruction workflow fixture acknowledged; not an external instruction." : c.action === "review_source" ? c.evidence : c.action === "activate_source" ? c.approval : c.reason;
  const decisionWrite = db.insert(clientInstructionDecisions).values({ id: createId(), tenantId: c.tenantId, matterId: c.matterId, instructionId: c.instructionId, action: c.action, fromStatus: input.fromStatus, toStatus: input.toStatus, reason, actorId: input.actor.userId, eventId: input.event.eventId, idempotencyKey: c.idempotencyKey, createdAt: now });
  if (c.action === "materialize_synthetic_source") {
    const objectKey = `${c.tenantId}/${c.matterId}/${c.evidenceId}/synthetic-client-instruction.pdf`, existing = await bucket.get(objectKey);
    if (existing) { const bytes = new Uint8Array(await existing.arrayBuffer()); if (await digest(bytes) !== SYNTHETIC_CLIENT_INSTRUCTION_SHA256) throw new Error("Existing client-instruction fixture checksum does not match immutable source identity"); }
    else await bucket.put(objectKey, buildSyntheticClientInstructionPdf(), { httpMetadata: { contentType: "application/pdf" }, customMetadata: { tenantId: c.tenantId, matterId: c.matterId, evidenceId: c.evidenceId, sha256: SYNTHETIC_CLIENT_INSTRUCTION_SHA256, custodyStatus: "trusted_synthetic_fixture" } });
    try { await db.batch([
      db.insert(documentEvidenceRecords).values({ id: c.evidenceId, tenantId: c.tenantId, matterId: c.matterId, sourceType: "synthetic_client_instruction_fixture", sourceId: `fixture-${c.instructionId}`, title: c.title, originalObjectKey: objectKey, originalSha256: SYNTHETIC_CLIENT_INSTRUCTION_SHA256, byteSize: SYNTHETIC_CLIENT_INSTRUCTION_BYTE_SIZE, mimeType: "application/pdf", pageCount: 1, custodyStatus: "trusted_synthetic_fixture", privilege: "none", confidentiality: "confidential", legalHoldRequired: false, createdBy: input.actor.userId, createdAt: now }),
      db.insert(clientInstructionSources).values({ id: c.instructionId, tenantId: c.tenantId, matterId: c.matterId, clientId: c.clientId, evidenceId: c.evidenceId, code: c.code, version: c.version, title: c.title, sourceSha256: SYNTHETIC_CLIENT_INSTRUCTION_SHA256, sourceObjectKey: objectKey, sourceByteSize: SYNTHETIC_CLIENT_INSTRUCTION_BYTE_SIZE, businessDays: c.businessDays, authorityCitation: c.authorityCitation, effectiveAt: dateOnly(c.effectiveDate), reviewBy: dateOnly(c.reviewDate), sourceMode: "deterministic_sandbox", status: "registered", revision: 1, createdBy: input.actor.userId, createdAt: now, updatedAt: now }), decisionWrite, eventWrite, outboxWrite,
    ] as never); } catch (error) { if (!existing) await bucket.delete(objectKey); throw error; }
    return { replayed: false, eventId: input.event.eventId };
  }
  const current = await readClientInstruction(c.tenantId, c.matterId, c.instructionId); if (!current || current.revision !== c.expectedRevision) throw new Error("Client instruction changed; refresh before retrying");
  const claim = db.insert(optimisticWriteClaims).values({ id: createId(), tenantId: c.tenantId, aggregateType: "client_instruction", aggregateId: c.instructionId, expectedRevision: c.expectedRevision, claimedRevision: c.expectedRevision + 1, actorId: input.actor.userId, eventId: input.event.eventId, idempotencyKey: c.idempotencyKey, createdAt: now });
  const patch = { status: input.toStatus as typeof current.status, revision: current.revision + 1, updatedAt: now, activatedLayerId: c.action === "activate_source" ? c.layerId : current.activatedLayerId, activatedBy: c.action === "activate_source" ? input.actor.userId : current.activatedBy, activatedAt: c.action === "activate_source" ? now : current.activatedAt, deactivatedBy: c.action === "deactivate_source" || (c.action === "review_source" && c.outcome === "rejected") ? input.actor.userId : current.deactivatedBy, deactivatedAt: c.action === "deactivate_source" || (c.action === "review_source" && c.outcome === "rejected") ? now : current.deactivatedAt, deactivationReason: c.action === "deactivate_source" ? c.reason : c.action === "review_source" && c.outcome === "rejected" ? c.evidence : current.deactivationReason };
  const writes: unknown[] = [claim, db.update(clientInstructionSources).set(patch).where(and(eq(clientInstructionSources.tenantId, c.tenantId), eq(clientInstructionSources.id, c.instructionId), eq(clientInstructionSources.revision, c.expectedRevision)))];
  if (c.action === "review_source") writes.push(db.insert(clientInstructionReviews).values({ id: c.reviewId, tenantId: c.tenantId, matterId: c.matterId, instructionId: c.instructionId, reviewType: c.reviewType, outcome: c.outcome, sourceSha256: current.sourceSha256, evidence: c.evidence, reviewerId: input.actor.userId, eventId: input.event.eventId, createdAt: now }));
  if (c.action === "activate_source") writes.push(db.insert(governancePolicyLayers).values({ id: c.layerId, tenantId: c.tenantId, matterId: c.matterId, code: current.code, version: current.version, scopeType: "client", scopeId: current.clientId, businessDays: current.businessDays, dayKind: "business", rollConvention: "next_business_day", authorityCitation: current.authorityCitation, effectiveAt: current.effectiveAt, reviewBy: current.reviewBy, contentStatus: current.sourceMode === "verified_evidence" ? "attorney_approved" : "synthetic_sandbox", status: "active", revision: 1, sourceKind: "client_instruction", sourceId: current.id, sourceSha256: current.sourceSha256, reason: c.approval, createdBy: input.actor.userId, eventId: input.event.eventId, createdAt: now, updatedAt: now }));
  if (c.action === "deactivate_source") { const [layer] = await db.select().from(governancePolicyLayers).where(and(eq(governancePolicyLayers.tenantId, c.tenantId), eq(governancePolicyLayers.id, current.activatedLayerId!))).limit(1); if (!layer || layer.status !== "active") throw new Error("Activated client policy layer is no longer active"); writes.push(db.insert(optimisticWriteClaims).values({ id: createId(), tenantId: c.tenantId, aggregateType: "governance_policy_layer", aggregateId: layer.id, expectedRevision: layer.revision, claimedRevision: layer.revision + 1, actorId: input.actor.userId, eventId: input.event.eventId, idempotencyKey: `${c.idempotencyKey}:layer`, createdAt: now }), db.update(governancePolicyLayers).set({ status: "superseded", revision: layer.revision + 1, updatedAt: now }).where(and(eq(governancePolicyLayers.tenantId, c.tenantId), eq(governancePolicyLayers.id, layer.id), eq(governancePolicyLayers.revision, layer.revision), eq(governancePolicyLayers.status, "active")))); }
  writes.push(decisionWrite, eventWrite, outboxWrite);
  try { await db.batch(writes as never); } catch (error) { const message = error instanceof Error ? error.message : String(error); if (message.includes("idx_governance_policy_layer_version") || message.includes("idx_client_instruction_review_type")) throw new OptimisticConcurrencyError(); rethrowOptimisticClaimConflict(error); }
  return { replayed: false, eventId: input.event.eventId };
}
const dateOnly = (value: string) => new Date(`${value}T12:00:00.000Z`);
async function digest(bytes: Uint8Array) { const copy = new Uint8Array(bytes.byteLength); copy.set(bytes); const hash = await crypto.subtle.digest("SHA-256", copy.buffer); return Array.from(new Uint8Array(hash), byte => byte.toString(16).padStart(2, "0")).join(""); }
