import { createId } from "@paralleldrive/cuid2";
import { and,asc,desc,eq } from "drizzle-orm";
import { getPreviewDb } from "../../db";
import { filingPacketDecisions,filingPacketDocuments,filingPacketValidations,filingPackets,jurisdictionFormDefinitions,previewEvents,previewOutbox } from "../../db/schema";
import { validateFilingPacket,type FilingPacketCommand,type FilingPacketState } from "@/domain/filings/packet";
import type { EventEnvelope } from "./events";
import type { RequestActor } from "./request-actor";
const REQUIRED=["primary_form","cover_sheet","separator_sheet","proof_of_service"];
export async function readFilingPacket(tenantId:string,matterId:string,id:string){const db=getPreviewDb(),[packet]=await db.select().from(filingPackets).where(and(eq(filingPackets.tenantId,tenantId),eq(filingPackets.matterId,matterId),eq(filingPackets.id,id))).limit(1);if(!packet)return null;const[documents,form]=await Promise.all([db.select().from(filingPacketDocuments).where(and(eq(filingPacketDocuments.tenantId,tenantId),eq(filingPacketDocuments.packetId,id))).orderBy(asc(filingPacketDocuments.position)),db.select().from(jurisdictionFormDefinitions).where(and(eq(jurisdictionFormDefinitions.tenantId,tenantId),eq(jurisdictionFormDefinitions.id,packet.formDefinitionId))).limit(1)]);return{...packet,documents,form:form[0]??null,formContentStatus:form[0]?.contentStatus??"pending_attorney_review",requiredDocumentKinds:form[0]?.requiredDocumentKinds??[]} as typeof packet&{documents:typeof documents;form:typeof form[number]|null;formContentStatus:FilingPacketState["formContentStatus"];requiredDocumentKinds:string[]};}
export async function readFilingPacketEvent(tenantId:string,key:string){const[x]=await getPreviewDb().select({eventId:previewEvents.eventId}).from(previewEvents).where(and(eq(previewEvents.tenantId,tenantId),eq(previewEvents.idempotencyKey,key))).limit(1);return x??null;}
export async function buildFilingPacketEvaluation(tenantId:string,matterId:string,id:string){const packet=await readFilingPacket(tenantId,matterId,id);if(!packet)throw new Error("Filing packet does not exist");return validateFilingPacket(packet as unknown as FilingPacketState);}
export async function filingPacketProjection(tenantId:string,matterId:string){const db=getPreviewDb(),packets=await db.select().from(filingPackets).where(and(eq(filingPackets.tenantId,tenantId),eq(filingPackets.matterId,matterId))).orderBy(asc(filingPackets.revisionNumber));const items=await Promise.all(packets.map(async packet=>{const[documents,validation,decisions,form]=await Promise.all([db.select().from(filingPacketDocuments).where(and(eq(filingPacketDocuments.tenantId,tenantId),eq(filingPacketDocuments.packetId,packet.id))).orderBy(asc(filingPacketDocuments.position)),db.select().from(filingPacketValidations).where(and(eq(filingPacketValidations.tenantId,tenantId),eq(filingPacketValidations.packetId,packet.id))).orderBy(desc(filingPacketValidations.createdAt)).limit(1),db.select().from(filingPacketDecisions).where(and(eq(filingPacketDecisions.tenantId,tenantId),eq(filingPacketDecisions.packetId,packet.id))).orderBy(asc(filingPacketDecisions.createdAt)),db.select().from(jurisdictionFormDefinitions).where(and(eq(jurisdictionFormDefinitions.tenantId,tenantId),eq(jurisdictionFormDefinitions.id,packet.formDefinitionId))).limit(1)]);return{...packet,documents,validation:validation[0]??null,decisions,form:form[0]??null};}));return{items};}
export async function persistFilingPacket(input:{command:FilingPacketCommand;fromStatus:string;toStatus:FilingPacketState["status"];event:EventEnvelope<Record<string,unknown>>;actor:RequestActor;evaluation?:ReturnType<typeof validateFilingPacket>}){const db=getPreviewDb(),{command}=input,now=new Date(input.event.occurredAt),eventWrite=db.insert(previewEvents).values({eventId:input.event.eventId,eventType:input.event.eventType,eventVersion:input.event.eventVersion,tenantId:input.event.tenantId,aggregateType:input.event.aggregateType,aggregateId:input.event.aggregateId,matterId:input.event.matterId,actorId:input.actor.userId,occurredAt:now,correlationId:input.event.correlationId,causationId:input.event.causationId,idempotencyKey:input.event.idempotencyKey,source:input.event.source,visibility:input.event.visibility,retentionPolicy:input.event.retentionPolicy,payload:input.event.payload}),outboxWrite=db.insert(previewOutbox).values({id:createId(),tenantId:command.tenantId,eventId:input.event.eventId,topic:"athena.filing_packets",payload:input.event,attempts:0,availableAt:now}),decisionWrite=db.insert(filingPacketDecisions).values({id:createId(),tenantId:command.tenantId,matterId:command.matterId,packetId:command.packetId,action:command.action,fromStatus:input.fromStatus,toStatus:input.toStatus,reason:reasonFor(command),actorId:input.actor.userId,eventId:input.event.eventId,idempotencyKey:command.idempotencyKey,createdAt:now});
 if(command.action==="create"){const formId=`${command.tenantId}-ca-pilot-msc-form-v1`,formWrite=db.insert(jurisdictionFormDefinitions).values({id:formId,tenantId:command.tenantId,jurisdiction:"CA",formCode:"pilot_msc_packet",version:1,officialTitle:"Synthetic MSC packet definition — not an official DWC title",effectiveAt:new Date("2026-01-01T00:00:00.000Z"),reviewBy:new Date("2026-12-31T00:00:00.000Z"),sourceAuthority:"Synthetic sandbox definition pending California attorney review",contentStatus:"synthetic_sandbox",requiredDocumentKinds:REQUIRED,createdAt:now}).onConflictDoNothing();await db.batch([formWrite,db.insert(filingPackets).values({id:command.packetId,tenantId:command.tenantId,matterId:command.matterId,proceedingId:command.proceedingId,formDefinitionId:formId,packetType:command.packetType,adjNumber:command.adjNumber,uan:command.uan,venue:command.venue,judge:command.judge,status:"draft",revisionNumber:1,submissionIdentity:command.submissionIdentity,revision:1,providerMode:"not_connected",createdBy:input.actor.userId,createdAt:now,updatedAt:now}),decisionWrite,eventWrite,outboxWrite]);return{replayed:false,eventId:input.event.eventId};}
 const current=await readFilingPacket(command.tenantId,command.matterId,command.packetId);if(!current||current.revision!==command.expectedRevision)throw new Error("Filing packet changed; refresh before retrying");
 if(command.action==="add_document"){await db.batch([db.insert(filingPacketDocuments).values({id:command.documentId,tenantId:command.tenantId,matterId:command.matterId,packetId:command.packetId,kind:command.kind,title:command.title,position:command.position,sha256:command.sha256,signatureStatus:command.signatureStatus,sourceDocumentId:command.sourceDocumentId,createdBy:input.actor.userId,createdAt:now}),db.update(filingPackets).set({status:"draft",revision:current.revision+1,updatedAt:now}).where(and(eq(filingPackets.tenantId,command.tenantId),eq(filingPackets.id,command.packetId),eq(filingPackets.revision,command.expectedRevision))),decisionWrite,eventWrite,outboxWrite]);}
 else if(command.action==="validate"){if(!input.evaluation)throw new Error("Validation result is required");await db.batch([db.insert(filingPacketValidations).values({id:input.event.eventId,tenantId:command.tenantId,matterId:command.matterId,packetId:command.packetId,packetRevision:current.revision,outcome:input.evaluation.outcome,checks:[...input.evaluation.checks],eventId:input.event.eventId,validatedBy:input.actor.userId,createdAt:now}),db.update(filingPackets).set({status:input.toStatus,revision:current.revision+1,updatedAt:now}).where(and(eq(filingPackets.tenantId,command.tenantId),eq(filingPackets.id,command.packetId),eq(filingPackets.revision,command.expectedRevision))),decisionWrite,eventWrite,outboxWrite]);}
 else if(command.action==="correct"){const documents=current.documents;await db.batch([db.update(filingPackets).set({status:"superseded",revision:current.revision+1,updatedAt:now}).where(and(eq(filingPackets.tenantId,command.tenantId),eq(filingPackets.id,command.packetId),eq(filingPackets.revision,command.expectedRevision))),db.insert(filingPackets).values({id:command.correctedPacketId,tenantId:command.tenantId,matterId:command.matterId,proceedingId:current.proceedingId,formDefinitionId:current.formDefinitionId,packetType:current.packetType,adjNumber:current.adjNumber,uan:current.uan,venue:current.venue,judge:current.judge,status:"draft",revisionNumber:current.revisionNumber+1,priorPacketId:current.id,correctionReason:command.reason,submissionIdentity:current.submissionIdentity,revision:1,providerMode:"not_connected",createdBy:input.actor.userId,createdAt:now,updatedAt:now}),...documents.map(x=>db.insert(filingPacketDocuments).values({id:createId(),tenantId:x.tenantId,matterId:x.matterId,packetId:command.correctedPacketId,kind:x.kind,title:x.title,position:x.position,sha256:x.sha256,signatureStatus:x.signatureStatus,sourceDocumentId:`${x.sourceDocumentId}-r${current.revisionNumber+1}`,createdBy:input.actor.userId,createdAt:now})),decisionWrite,eventWrite,outboxWrite] as never);}
 else{const patch={status:input.toStatus,revision:current.revision+1,updatedAt:now,approvedBy:command.action==="approve"?input.actor.userId:current.approvedBy,approvedAt:command.action==="approve"?now:current.approvedAt,providerMode:command.action==="record_status"?command.providerMode:current.providerMode,externalStatusEvidence:command.action==="record_status"?command.evidence:current.externalStatusEvidence,externalReference:command.action==="record_status"?command.externalReference:current.externalReference};await db.batch([db.update(filingPackets).set(patch).where(and(eq(filingPackets.tenantId,command.tenantId),eq(filingPackets.id,command.packetId),eq(filingPackets.revision,command.expectedRevision))),decisionWrite,eventWrite,outboxWrite]);}
 return{replayed:false,eventId:input.event.eventId};}
function reasonFor(command:FilingPacketCommand){if("reason" in command)return command.reason;if(command.action==="record_status")return command.evidence;if(command.action==="add_document")return `${command.kind}:${command.sourceDocumentId}`;return null;}
