import { createId } from "@paralleldrive/cuid2";
import { and,asc,desc,eq } from "drizzle-orm";
import { getPreviewDb } from "../../db";
import { previewEvents,previewOutbox,proceedingAssessments,proceedingDecisions,proceedingFindings,proceedingReadinessItems,proceedings } from "../../db/schema";
import { evaluateProceedingReadiness,proceedingItemCodes,proceedingItemDefinitions,type ProceedingCommand,type ProceedingItemState } from "@/domain/proceedings/readiness";
import type { EventEnvelope } from "./events";
import type { RequestActor } from "./request-actor";

export async function readProceeding(tenantId:string,matterId:string,id:string){const[x]=await getPreviewDb().select().from(proceedings).where(and(eq(proceedings.tenantId,tenantId),eq(proceedings.matterId,matterId),eq(proceedings.id,id))).limit(1);return x??null;}
export async function readProceedingItem(tenantId:string,proceedingId:string,code:string){const[x]=await getPreviewDb().select().from(proceedingReadinessItems).where(and(eq(proceedingReadinessItems.tenantId,tenantId),eq(proceedingReadinessItems.proceedingId,proceedingId),eq(proceedingReadinessItems.code,code))).limit(1);return x as (ProceedingItemState&{id:string})|undefined;}
export async function readProceedingEvent(tenantId:string,key:string){const[x]=await getPreviewDb().select({eventId:previewEvents.eventId}).from(previewEvents).where(and(eq(previewEvents.tenantId,tenantId),eq(previewEvents.idempotencyKey,key))).limit(1);return x??null;}
export async function buildProceedingEvaluation(tenantId:string,proceedingId:string){const rows=await getPreviewDb().select().from(proceedingReadinessItems).where(and(eq(proceedingReadinessItems.tenantId,tenantId),eq(proceedingReadinessItems.proceedingId,proceedingId))).orderBy(asc(proceedingReadinessItems.code));return evaluateProceedingReadiness(rows as ProceedingItemState[],false);}
export async function proceedingProjection(tenantId:string,matterId:string){const db=getPreviewDb(),items=await db.select().from(proceedings).where(and(eq(proceedings.tenantId,tenantId),eq(proceedings.matterId,matterId))).orderBy(asc(proceedings.scheduledAt));const enriched=await Promise.all(items.map(async proceeding=>{const[checks,assessment]=await Promise.all([db.select().from(proceedingReadinessItems).where(and(eq(proceedingReadinessItems.tenantId,tenantId),eq(proceedingReadinessItems.proceedingId,proceeding.id))).orderBy(asc(proceedingReadinessItems.code)),db.select().from(proceedingAssessments).where(and(eq(proceedingAssessments.tenantId,tenantId),eq(proceedingAssessments.proceedingId,proceeding.id))).orderBy(desc(proceedingAssessments.createdAt)).limit(1)]);const findings=assessment[0]?await db.select().from(proceedingFindings).where(and(eq(proceedingFindings.tenantId,tenantId),eq(proceedingFindings.assessmentId,assessment[0].id))):[];return{...proceeding,checks,assessment:assessment[0]??null,findings};}));return{items:enriched};}

export async function persistProceeding(input:{command:ProceedingCommand;event:EventEnvelope<Record<string,unknown>>;actor:RequestActor;evaluation?:ReturnType<typeof evaluateProceedingReadiness>}){
  const db=getPreviewDb(),{command}=input,now=new Date(input.event.occurredAt),eventWrite=db.insert(previewEvents).values({eventId:input.event.eventId,eventType:input.event.eventType,eventVersion:input.event.eventVersion,tenantId:input.event.tenantId,aggregateType:input.event.aggregateType,aggregateId:input.event.aggregateId,matterId:input.event.matterId,actorId:input.actor.userId,occurredAt:now,correlationId:input.event.correlationId,causationId:input.event.causationId,idempotencyKey:input.event.idempotencyKey,source:input.event.source,visibility:input.event.visibility,retentionPolicy:input.event.retentionPolicy,payload:input.event.payload}),outboxWrite=db.insert(previewOutbox).values({id:createId(),tenantId:command.tenantId,eventId:input.event.eventId,topic:"athena.proceedings",payload:input.event,attempts:0,availableAt:now});
  const itemCode="itemCode" in command?command.itemCode:null,evidence="evidence" in command?command.evidence:null,decisionWrite=db.insert(proceedingDecisions).values({id:createId(),tenantId:command.tenantId,matterId:command.matterId,proceedingId:command.proceedingId,action:command.action,itemCode,fromStatus:itemCode?"missing":null,toStatus:command.action==="verify_item"?"verified":command.action==="mark_not_required"?"not_required":null,evidence,actorId:input.actor.userId,eventId:input.event.eventId,idempotencyKey:command.idempotencyKey,createdAt:now});
  if(command.action==="create"){
    const rows=proceedingItemCodes.map(code=>{const definition=proceedingItemDefinitions[code];return{id:createId(),tenantId:command.tenantId,matterId:command.matterId,proceedingId:command.proceedingId,code,label:definition.label,category:definition.category,severity:definition.severity,status:"missing" as const,providerMode:definition.providerMode,revision:1,createdAt:now,updatedAt:now};});
    await db.batch([db.insert(proceedings).values({id:command.proceedingId,tenantId:command.tenantId,matterId:command.matterId,proceedingType:command.proceedingType,title:command.title,scheduledAt:new Date(command.scheduledAt),venue:command.venue,sourceType:command.sourceType,sourceId:command.sourceId,contentStatus:command.contentStatus,status:"scheduled",revision:1,createdBy:input.actor.userId,createdAt:now,updatedAt:now}),...rows.map(row=>db.insert(proceedingReadinessItems).values(row)),decisionWrite,eventWrite,outboxWrite] as never);return{replayed:false,eventId:input.event.eventId};
  }
  if(command.action==="verify_item"||command.action==="mark_not_required"){
    const current=await readProceedingItem(command.tenantId,command.proceedingId,command.itemCode);if(!current||current.revision!==command.expectedRevision)throw new Error("Readiness item changed; refresh before retrying");
    await db.batch([db.update(proceedingReadinessItems).set({status:command.action==="verify_item"?"verified":"not_required",evidence:command.evidence,evidenceType:command.action==="verify_item"?command.evidenceType:"human_attestation",evidenceId:command.action==="verify_item"?command.evidenceId:input.event.eventId,providerMode:command.action==="verify_item"?command.providerMode:current.providerMode,verifiedBy:input.actor.userId,verifiedAt:now,revision:current.revision+1,updatedAt:now}).where(and(eq(proceedingReadinessItems.tenantId,command.tenantId),eq(proceedingReadinessItems.id,current.id),eq(proceedingReadinessItems.revision,command.expectedRevision))),decisionWrite,eventWrite,outboxWrite]);return{replayed:false,eventId:input.event.eventId};
  }
  if(!input.evaluation)throw new Error("Proceeding evaluation is required");const assessmentId=input.event.eventId;
  await db.batch([db.insert(proceedingAssessments).values({id:assessmentId,tenantId:command.tenantId,matterId:command.matterId,proceedingId:command.proceedingId,state:input.evaluation.state,passCount:input.evaluation.passCount,gapCount:input.evaluation.gapCount,blockedCount:input.evaluation.blockedCount,dataAsOf:now,evaluatedBy:input.actor.userId,nonAutonomous:true,createdAt:now}),...input.evaluation.findings.map(x=>db.insert(proceedingFindings).values({id:createId(),tenantId:command.tenantId,matterId:command.matterId,proceedingId:command.proceedingId,assessmentId,code:x.code,category:x.category,status:x.status,severity:x.severity,explanation:x.explanation,evidenceType:x.evidenceType??null,evidenceId:x.evidenceId??null,createdAt:now})),decisionWrite,eventWrite,outboxWrite] as never);return{replayed:false,eventId:input.event.eventId,assessmentId};
}
