import { createId } from "@paralleldrive/cuid2";
import { and, asc, desc, eq } from "drizzle-orm";
import { getPreviewDb } from "../../db";
import { previewEvents, previewOutbox, scaleAssessments, scaleDecisions, scaleMeasurements } from "../../db/schema";
import { scaleBlockingGaps, type ScaleAuditCommand, type ScaleMeasurement } from "@/domain/platform/scale-audit";
import type { EventEnvelope } from "./events";
import type { RequestActor } from "./request-actor";
export async function readScaleAssessment(t: string, id: string) { const [row] = await getPreviewDb().select().from(scaleAssessments).where(and(eq(scaleAssessments.tenantId, t), eq(scaleAssessments.id, id))).limit(1); return row ?? null; }
export async function readScaleEvent(t: string, key: string) { const [row] = await getPreviewDb().select({ eventId: previewEvents.eventId }).from(previewEvents).where(and(eq(previewEvents.tenantId, t), eq(previewEvents.idempotencyKey, key))).limit(1); return row ?? null; }
export async function scaleProjection(t: string) { const db = getPreviewDb(), [assessments, measurements, decisions] = await Promise.all([db.select().from(scaleAssessments).where(eq(scaleAssessments.tenantId, t)).orderBy(desc(scaleAssessments.createdAt)), db.select().from(scaleMeasurements).where(eq(scaleMeasurements.tenantId, t)).orderBy(asc(scaleMeasurements.createdAt)), db.select().from(scaleDecisions).where(eq(scaleDecisions.tenantId, t)).orderBy(asc(scaleDecisions.createdAt))]); return { assessments, measurements, decisions }; }
export async function persistScaleAudit(input: { command: ScaleAuditCommand; fromStatus: string; toStatus: "measured" | "reviewed_with_gaps" | "rejected"; measurements?: ScaleMeasurement[]; event: EventEnvelope<Record<string, unknown>>; actor: RequestActor }) {
  const db = getPreviewDb(), c = input.command, now = new Date(input.event.occurredAt);
  const eventWrite = db.insert(previewEvents).values({ eventId: input.event.eventId, eventType: input.event.eventType, eventVersion: input.event.eventVersion, tenantId: c.tenantId, aggregateType: input.event.aggregateType, aggregateId: c.assessmentId, matterId: null, actorId: input.actor.userId, occurredAt: now, correlationId: input.event.correlationId, causationId: input.event.causationId, idempotencyKey: input.event.idempotencyKey, source: input.event.source, visibility: input.event.visibility, retentionPolicy: input.event.retentionPolicy, payload: input.event.payload });
  const outboxWrite = db.insert(previewOutbox).values({ id: createId(), tenantId: c.tenantId, eventId: input.event.eventId, topic: "athena.scale", payload: input.event, attempts: 0, availableAt: now });
  const decisionWrite = db.insert(scaleDecisions).values({ id: createId(), tenantId: c.tenantId, assessmentId: c.assessmentId, action: c.action, fromStatus: input.fromStatus, toStatus: input.toStatus, reason: c.action === "run_local_benchmark" ? "Ran bounded local synthetic algorithms; production and async paths remain unproven." : c.reason, actorId: input.actor.userId, eventId: input.event.eventId, idempotencyKey: c.idempotencyKey, createdAt: now });
  const writes: unknown[] = [];
  if (c.action === "run_local_benchmark") { if (!input.measurements?.length) throw new Error("Benchmark measurements are required"); const failed = input.measurements.some((m) => m.status === "fail"); writes.push(db.insert(scaleAssessments).values({ id: c.assessmentId, tenantId: c.tenantId, environment: "local_worker_synthetic", workloadProfile: c.workloadProfile, status: "measured", overallOutcome: failed ? "fail" : "conditional", blockingGaps: scaleBlockingGaps, maxPageSize: c.maxPageSize, outboxBatchLimit: c.outboxBatchLimit, archiveByteLimit: c.archiveByteLimit, archiveRowLimit: c.archiveRowLimit, revision: 1, reviewedBy: null, reviewedAt: null, createdBy: input.actor.userId, createdAt: now, updatedAt: now }), ...input.measurements.map((m) => db.insert(scaleMeasurements).values({ id: createId(), tenantId: c.tenantId, assessmentId: c.assessmentId, metricCode: m.metricCode, targetMs: m.targetMs, measuredMs: m.measuredMs, status: m.status, method: m.method, sampleSize: m.sampleSize, limitation: m.limitation, createdAt: now })) ); }
  else { const current = await readScaleAssessment(c.tenantId, c.assessmentId); if (!current || current.revision !== c.expectedRevision) throw new Error("Scale assessment changed; refresh before retrying"); writes.push(db.update(scaleAssessments).set({ status: input.toStatus, overallOutcome: c.outcome === "reject" ? "fail" : current.overallOutcome, revision: current.revision + 1, reviewedBy: input.actor.userId, reviewedAt: now, updatedAt: now }).where(and(eq(scaleAssessments.tenantId, c.tenantId), eq(scaleAssessments.id, c.assessmentId), eq(scaleAssessments.revision, c.expectedRevision)))); }
  await db.batch([...(writes as never[]), decisionWrite, eventWrite, outboxWrite] as never); return { replayed: false, eventId: input.event.eventId };
}
