import { createId } from "@paralleldrive/cuid2";
import { and, asc, desc, eq } from "drizzle-orm";
import { getPreviewDb } from "../../db";
import { authorityApprovalRequests, authorityApprovalResponses, authorityCandidates, authorityLedger, integrationHandoffs, matterTasks, previewEvents, previewOutbox, structuredAuthorityDecisions } from "../../db/schema";
import type { StructuredAuthorityCommand, StructuredAuthorityStatus } from "@/domain/authority/structured-approval";
import type { EventEnvelope } from "./events";
import type { RequestActor } from "./request-actor";
export async function readStructuredAuthorityRequest(t: string, m: string, id: string) { const [row] = await getPreviewDb().select().from(authorityApprovalRequests).where(and(eq(authorityApprovalRequests.tenantId, t), eq(authorityApprovalRequests.matterId, m), eq(authorityApprovalRequests.id, id))).limit(1); return row ?? null; }
export async function readStructuredAuthorityResponse(t: string, m: string, id: string) { const [row] = await getPreviewDb().select().from(authorityApprovalResponses).where(and(eq(authorityApprovalResponses.tenantId, t), eq(authorityApprovalResponses.matterId, m), eq(authorityApprovalResponses.id, id))).limit(1); return row ?? null; }
export async function readStructuredAuthorityEvent(t: string, key: string) { const [row] = await getPreviewDb().select({ eventId: previewEvents.eventId }).from(previewEvents).where(and(eq(previewEvents.tenantId, t), eq(previewEvents.idempotencyKey, key))).limit(1); return row ?? null; }
export async function structuredAuthorityProjection(t: string, m: string) { const db = getPreviewDb(), [requests, responses, decisions, ledger] = await Promise.all([
  db.select().from(authorityApprovalRequests).where(and(eq(authorityApprovalRequests.tenantId, t), eq(authorityApprovalRequests.matterId, m))).orderBy(desc(authorityApprovalRequests.createdAt)),
  db.select().from(authorityApprovalResponses).where(and(eq(authorityApprovalResponses.tenantId, t), eq(authorityApprovalResponses.matterId, m))).orderBy(desc(authorityApprovalResponses.createdAt)),
  db.select().from(structuredAuthorityDecisions).where(and(eq(structuredAuthorityDecisions.tenantId, t), eq(structuredAuthorityDecisions.matterId, m))).orderBy(asc(structuredAuthorityDecisions.createdAt)),
  db.select().from(authorityLedger).where(and(eq(authorityLedger.tenantId, t), eq(authorityLedger.matterId, m))).orderBy(desc(authorityLedger.verifiedAt)),
]); return { requests, responses, decisions, current: ledger.find((item) => item.status === "confirmed") ?? null }; }
export async function persistStructuredAuthority(input: { command: StructuredAuthorityCommand; fromStatus: string; toStatus: StructuredAuthorityStatus; event: EventEnvelope<Record<string, unknown>>; actor: RequestActor }) {
  const db = getPreviewDb(), c = input.command, now = new Date(input.event.occurredAt);
  const eventWrite = db.insert(previewEvents).values({ eventId: input.event.eventId, eventType: input.event.eventType, eventVersion: input.event.eventVersion, tenantId: c.tenantId, aggregateType: input.event.aggregateType, aggregateId: c.requestId, matterId: c.matterId, actorId: input.actor.userId, occurredAt: now, correlationId: input.event.correlationId, causationId: input.event.causationId, idempotencyKey: input.event.idempotencyKey, source: input.event.source, visibility: input.event.visibility, retentionPolicy: input.event.retentionPolicy, payload: input.event.payload });
  const outboxWrite = db.insert(previewOutbox).values({ id: createId(), tenantId: c.tenantId, eventId: input.event.eventId, topic: "athena.authority_approval", payload: input.event, attempts: 0, availableAt: now });
  const decisionWrite = db.insert(structuredAuthorityDecisions).values({ id: createId(), tenantId: c.tenantId, matterId: c.matterId, requestId: c.requestId, action: c.action, fromStatus: input.fromStatus, toStatus: input.toStatus, reason: reason(c), actorId: input.actor.userId, eventId: input.event.eventId, idempotencyKey: c.idempotencyKey, createdAt: now });
  const writes: unknown[] = [];
  if (c.action === "create_request") writes.push(db.insert(authorityApprovalRequests).values({ id: c.requestId, tenantId: c.tenantId, matterId: c.matterId, requestedAmountCents: c.requestedAmountCents, currency: c.currency, settlementStructure: c.settlementStructure, scope: c.scope, includes: c.includes, excludes: c.excludes, conditions: c.conditions, examinerName: c.examinerName, examinerEmail: c.examinerEmail, examinerOrganization: c.examinerOrganization, requestedExpiresAt: new Date(c.requestedExpiresAt), status: "draft", providerMode: "not_connected", approvedBy: null, approvedAt: null, responseId: null, ledgerId: null, revision: 1, createdBy: input.actor.userId, createdAt: now, updatedAt: now })); else {
    const current = await readStructuredAuthorityRequest(c.tenantId, c.matterId, c.requestId); if (!current || current.revision !== c.expectedRevision) throw new Error("Authority approval request changed; refresh before retrying");
    const patch: Record<string, unknown> = { status: input.toStatus, revision: current.revision + 1, updatedAt: now };
    if (c.action === "approve_request") Object.assign(patch, { approvedBy: input.actor.userId, approvedAt: now });
    if (c.action === "attempt_delivery") writes.push(db.insert(integrationHandoffs).values({ id: createId(), tenantId: c.tenantId, matterId: c.matterId, runId: c.requestId, provider: "client_authority_approval", operation: "deliver_secure_authority_request", status: "blocked_not_connected", providerMode: "not_connected", retryable: true, activationRequirement: "Approved external identity, secure approval page, verified examiner roster, MFA/session policy, signed response evidence, notification delivery, revocation, and reconciliation are required.", createdAt: now }));
    if (c.action === "record_human_response") {
      Object.assign(patch, { responseId: c.responseId, providerMode: "human_verified_external" });
      writes.push(db.insert(authorityApprovalResponses).values({ id: c.responseId, tenantId: c.tenantId, matterId: c.matterId, requestId: c.requestId, outcome: c.outcome, amountCents: c.amountCents ?? null, currency: c.currency, settlementStructure: c.settlementStructure ?? null, scope: c.scope ?? null, includes: c.includes, excludes: c.excludes, conditions: c.conditions, negotiationThresholdCents: c.negotiationThresholdCents ?? null, responderName: c.responderName, responderRole: c.responderRole, responderOrganization: c.responderOrganization, effectiveAt: c.effectiveAt ? new Date(c.effectiveAt) : null, expiresAt: c.expiresAt ? new Date(c.expiresAt) : null, evidence: c.evidence, providerMode: "human_verified_external", verifiedBy: input.actor.userId, createdAt: now }));
    }
    if (c.action === "confirm_response") {
      const response = await readStructuredAuthorityResponse(c.tenantId, c.matterId, c.responseId); if (!response?.amountCents || !response.settlementStructure || !response.scope || !response.effectiveAt || response.outcome === "declined") throw new Error("Complete verified approval response is required");
      Object.assign(patch, { ledgerId: c.ledgerId });
      writes.push(
        db.update(authorityLedger).set({ status: "superseded", supersededById: c.ledgerId, revision: 2 }).where(and(eq(authorityLedger.tenantId, c.tenantId), eq(authorityLedger.matterId, c.matterId), eq(authorityLedger.status, "confirmed"))),
        db.insert(authorityCandidates).values({ id: c.candidateId, tenantId: c.tenantId, matterId: c.matterId, classification: "grant", amountCents: response.amountCents, currency: response.currency, settlementStructure: response.settlementStructure, scope: response.scope, includes: response.includes, excludes: response.excludes, conditions: response.conditions, negotiationThresholdCents: response.negotiationThresholdCents, grantorName: response.responderName, grantorRole: response.responderRole, grantorOrganization: response.responderOrganization, effectiveAt: response.effectiveAt, expiresAt: response.expiresAt, sourceType: "human_verified_structured_response", sourceId: response.id, sourceExcerpt: response.evidence, status: "confirmed", revision: 1, createdAt: now, updatedAt: now }),
        db.insert(authorityLedger).values({ id: c.ledgerId, tenantId: c.tenantId, matterId: c.matterId, sourceCandidateId: c.candidateId, amountCents: response.amountCents, currency: response.currency, settlementStructure: response.settlementStructure, scope: response.scope, includes: response.includes, excludes: response.excludes, conditions: response.conditions, negotiationThresholdCents: response.negotiationThresholdCents, grantorName: response.responderName, grantorRole: response.responderRole, grantorOrganization: response.responderOrganization, effectiveAt: response.effectiveAt, expiresAt: response.expiresAt, status: "confirmed", verifiedBy: input.actor.userId, verifiedAt: now, supersededById: null, revision: 1 }),
        db.insert(matterTasks).values({ id: c.expirationTaskId, tenantId: c.tenantId, matterId: c.matterId, title: "Review structured settlement authority before expiration", taskType: "authority_expiration_review", priority: "critical", ownerId: input.actor.userId, dueAt: response.expiresAt ?? current.requestedExpiresAt, status: "open", blockerReason: null, completionEvidence: null, completedBy: null, completedAt: null, cancelledBy: null, cancelledAt: null, cancellationReason: null, revision: 1, createdAt: now, updatedAt: now }),
      );
    }
    writes.push(db.update(authorityApprovalRequests).set(patch).where(and(eq(authorityApprovalRequests.tenantId, c.tenantId), eq(authorityApprovalRequests.id, c.requestId), eq(authorityApprovalRequests.revision, c.expectedRevision))));
  }
  await db.batch([...(writes as never[]), decisionWrite, eventWrite, outboxWrite] as never); return { replayed: false, eventId: input.event.eventId };
}
function reason(c: StructuredAuthorityCommand) { if ("reason" in c) return c.reason; if (c.action === "record_human_response") return c.evidence; return `Attorney prepared a synthetic structured authority request for ${c.examinerName}.`; }
