import { createId } from "@paralleldrive/cuid2";
import { and, asc, eq } from "drizzle-orm";
import { getPreviewDb } from "../../db";
import { candidateTimeEntries, integrationHandoffs, previewEvents, previewOutbox, telephonyContacts, telephonyDecisions, telephonyInteractions } from "../../db/schema";
import type { TelephonyCommand, TelephonyStatus } from "@/domain/telephony/lifecycle";
import type { EventEnvelope } from "./events";
import type { RequestActor } from "./request-actor";
export async function readTelephonyContact(t: string, m: string, id: string) { const [row] = await getPreviewDb().select().from(telephonyContacts).where(and(eq(telephonyContacts.tenantId, t), eq(telephonyContacts.matterId, m), eq(telephonyContacts.id, id))).limit(1); return row ?? null; }
export async function readTelephonyEvent(t: string, key: string) { const [row] = await getPreviewDb().select({ eventId: previewEvents.eventId }).from(previewEvents).where(and(eq(previewEvents.tenantId, t), eq(previewEvents.idempotencyKey, key))).limit(1); return row ?? null; }
export async function telephonyProjection(t: string, m: string) { const db = getPreviewDb(), [contacts, interactions, decisions, times] = await Promise.all([
  db.select().from(telephonyContacts).where(and(eq(telephonyContacts.tenantId, t), eq(telephonyContacts.matterId, m))),
  db.select().from(telephonyInteractions).where(and(eq(telephonyInteractions.tenantId, t), eq(telephonyInteractions.matterId, m))).orderBy(asc(telephonyInteractions.occurredAt)),
  db.select().from(telephonyDecisions).where(and(eq(telephonyDecisions.tenantId, t), eq(telephonyDecisions.matterId, m))).orderBy(asc(telephonyDecisions.createdAt)),
  db.select({ id: candidateTimeEntries.id, runId: candidateTimeEntries.runId, minutes: candidateTimeEntries.minutes, narrative: candidateTimeEntries.narrative, status: candidateTimeEntries.status, confirmedBy: candidateTimeEntries.confirmedBy }).from(candidateTimeEntries).where(and(eq(candidateTimeEntries.tenantId, t), eq(candidateTimeEntries.matterId, m))),
]); return { contacts, interactions, decisions, times }; }
export async function persistTelephony(input: { command: TelephonyCommand; fromStatus: string; toStatus: TelephonyStatus; event: EventEnvelope<Record<string, unknown>>; actor: RequestActor }) {
  const db = getPreviewDb(), c = input.command, now = new Date(input.event.occurredAt);
  const eventWrite = db.insert(previewEvents).values({ eventId: input.event.eventId, eventType: input.event.eventType, eventVersion: input.event.eventVersion, tenantId: c.tenantId, aggregateType: input.event.aggregateType, aggregateId: c.contactId, matterId: c.matterId, actorId: input.actor.userId, occurredAt: now, correlationId: input.event.correlationId, causationId: input.event.causationId, idempotencyKey: input.event.idempotencyKey, source: input.event.source, visibility: input.event.visibility, retentionPolicy: input.event.retentionPolicy, payload: input.event.payload });
  const outboxWrite = db.insert(previewOutbox).values({ id: createId(), tenantId: c.tenantId, eventId: input.event.eventId, topic: "athena.telephony", payload: input.event, attempts: 0, availableAt: now });
  const decisionWrite = db.insert(telephonyDecisions).values({ id: createId(), tenantId: c.tenantId, matterId: c.matterId, contactId: c.contactId, action: c.action, fromStatus: input.fromStatus, toStatus: input.toStatus, reason: reason(c), actorId: input.actor.userId, eventId: input.event.eventId, idempotencyKey: c.idempotencyKey, createdAt: now });
  const writes: unknown[] = [];
  if (c.action === "configure_contact") writes.push(db.insert(telephonyContacts).values({ id: c.contactId, tenantId: c.tenantId, matterId: c.matterId, contactName: c.contactName, contactNumber: c.contactNumber, tenantNumber: c.tenantNumber, smsConsentStatus: "unknown", voiceConsentStatus: "unknown", consentEvidence: null, recordingAllowed: false, provider: "provider_neutral_telephony", providerMode: "not_connected", status: "configured", candidateTimeId: null, revision: 1, createdBy: input.actor.userId, createdAt: now, updatedAt: now })); else {
    const current = await readTelephonyContact(c.tenantId, c.matterId, c.contactId); if (!current || current.revision !== c.expectedRevision) throw new Error("Telephony contact changed; refresh before retrying");
    const patch: Record<string, unknown> = { status: input.toStatus, revision: current.revision + 1, updatedAt: now };
    if (c.action === "record_consents") Object.assign(patch, { smsConsentStatus: "opted_in", voiceConsentStatus: "consented", consentEvidence: c.evidence, recordingAllowed: false, providerMode: "human_verified_sandbox" });
    if (c.action === "draft_sms") writes.push(db.insert(telephonyInteractions).values({ id: c.interactionId, tenantId: c.tenantId, matterId: c.matterId, contactId: c.contactId, channel: "sms", direction: "outbound", interactionType: "message", body: c.body, bodySha256: await digest(c.body), durationSeconds: null, recordingStatus: "not_applicable", status: "draft", providerMode: "not_connected", deliveryAttempted: false, approvedBy: null, occurredAt: now, createdAt: now }));
    if (c.action === "approve_sms") writes.push(db.update(telephonyInteractions).set({ status: "approved", approvedBy: input.actor.userId }).where(and(eq(telephonyInteractions.tenantId, c.tenantId), eq(telephonyInteractions.contactId, c.contactId), eq(telephonyInteractions.id, c.interactionId), eq(telephonyInteractions.status, "draft"))));
    if (c.action === "attempt_sms_delivery") {
      writes.push(db.update(telephonyInteractions).set({ status: "blocked_not_connected", providerMode: "not_connected", deliveryAttempted: false }).where(and(eq(telephonyInteractions.tenantId, c.tenantId), eq(telephonyInteractions.contactId, c.contactId), eq(telephonyInteractions.id, c.interactionId), eq(telephonyInteractions.status, "approved"))));
      writes.push(db.insert(integrationHandoffs).values({ id: createId(), tenantId: c.tenantId, matterId: c.matterId, runId: c.contactId, provider: "provider_neutral_telephony", operation: "send_sms", status: "blocked_not_connected", providerMode: "not_connected", retryable: true, activationRequirement: "Approved provider and numbers, OAuth/credentials, consent and HELP/STOP policy, delivery status, retention, revocation, and reconciliation are required.", createdAt: now }));
    }
    if (c.action === "record_help" || c.action === "record_stop") {
      const stop = c.action === "record_stop", interactionId = stop ? c.stopInteractionId : c.helpInteractionId, occurredAt = new Date(c.receivedAt);
      if (stop) Object.assign(patch, { smsConsentStatus: "opted_out" });
      writes.push(db.insert(telephonyInteractions).values({ id: interactionId, tenantId: c.tenantId, matterId: c.matterId, contactId: c.contactId, channel: "sms", direction: "inbound", interactionType: stop ? "stop" : "help", body: stop ? "STOP" : "HELP", bodySha256: await digest(stop ? "STOP" : "HELP"), durationSeconds: null, recordingStatus: "not_applicable", status: "preserved", providerMode: "human_verified_sandbox", deliveryAttempted: false, approvedBy: null, occurredAt, createdAt: now }));
    }
    if (c.action === "record_call_metadata") writes.push(db.insert(telephonyInteractions).values({ id: c.callInteractionId, tenantId: c.tenantId, matterId: c.matterId, contactId: c.contactId, channel: "voice", direction: "outbound", interactionType: "call_metadata", body: c.evidence, bodySha256: await digest(c.evidence), durationSeconds: c.durationSeconds, recordingStatus: "disabled", status: "preserved", providerMode: "human_verified_sandbox", deliveryAttempted: false, approvedBy: null, occurredAt: new Date(c.occurredAt), createdAt: now }));
    if (c.action === "associate_call") writes.push(db.update(telephonyInteractions).set({ status: "filed", approvedBy: input.actor.userId }).where(and(eq(telephonyInteractions.tenantId, c.tenantId), eq(telephonyInteractions.contactId, c.contactId), eq(telephonyInteractions.id, c.callInteractionId), eq(telephonyInteractions.interactionType, "call_metadata"))));
    if (c.action === "confirm_time") { Object.assign(patch, { candidateTimeId: c.candidateTimeId }); writes.push(db.insert(candidateTimeEntries).values({ id: c.candidateTimeId, tenantId: c.tenantId, matterId: c.matterId, runId: c.contactId, minutes: c.minutes, narrative: c.narrative, taskCode: c.taskCode, activityCode: c.activityCode, status: "confirmed", confirmedBy: input.actor.userId, confirmedAt: now })); }
    writes.push(db.update(telephonyContacts).set(patch).where(and(eq(telephonyContacts.tenantId, c.tenantId), eq(telephonyContacts.id, c.contactId), eq(telephonyContacts.revision, c.expectedRevision))));
  }
  await db.batch([...(writes as never[]), decisionWrite, eventWrite, outboxWrite] as never); return { replayed: false, eventId: input.event.eventId };
}
function reason(c: TelephonyCommand) { if ("reason" in c) return c.reason; if ("evidence" in c) return c.evidence; if (c.action === "draft_sms") return "Human-authored synthetic outbound SMS draft preserved for attorney review."; return "Configured a provider-neutral synthetic telephony contact with recording disabled."; }
async function digest(value: string) { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(bytes), (b) => b.toString(16).padStart(2, "0")).join(""); }
