import { decideProceeding,proceedingCommand } from "@/domain/proceedings/readiness";
import { authorizePersistedMatter } from "@/platform/access-policy-persistence";
import { buildProceedingEvaluation,persistProceeding,proceedingProjection,readProceeding,readProceedingEvent,readProceedingItem } from "@/platform/proceeding-persistence";
import { GOLDEN_MATTER_ID,PILOT_TENANT_ID,pilotContext } from "@/platform/pilot-context";
import { enforceRateLimit,RateLimitError,rateLimitResponse } from "@/platform/rate-limit-persistence";
import { requestActor } from "@/platform/request-actor";
import { assertTrustedWriteOrigin,RequestSecurityError } from "@/platform/request-security";
import { AuthorizationError } from "@/platform/tenant-context";
const limitation="Proceeding readiness is non-autonomous. California content remains pending attorney review, and EAMS is disconnected; filing status is never inferred or represented as provider-confirmed.";
export async function GET(request:Request){try{const actor=requestActor(request);if(!actor)return Response.json({error:"Authentication required"},{status:401});await authorizePersistedMatter(pilotContext(actor),PILOT_TENANT_ID,GOLDEN_MATTER_ID);return Response.json({...await proceedingProjection(PILOT_TENANT_ID,GOLDEN_MATTER_ID),limitation});}catch(e){if(e instanceof AuthorizationError)return Response.json({error:"Access denied"},{status:403});return Response.json({error:"Proceedings could not be read"},{status:500});}}
export async function POST(request:Request){try{assertTrustedWriteOrigin(request);const actor=requestActor(request);if(!actor)return Response.json({error:"Authentication required"},{status:401});await enforceRateLimit({tenantId:PILOT_TENANT_ID,actorId:actor.userId,action:"proceedings.command",policy:{limit:40,windowMs:60_000}});const context=pilotContext(actor),command=proceedingCommand.parse(await request.json());await authorizePersistedMatter(context,command.tenantId,command.matterId);const prior=await readProceedingEvent(command.tenantId,command.idempotencyKey);if(prior)return Response.json({event:null,persistence:{replayed:true,eventId:prior.eventId},...await proceedingProjection(command.tenantId,command.matterId),limitation});const proceeding=await readProceeding(command.tenantId,command.matterId,command.proceedingId),item="itemCode" in command?await readProceedingItem(command.tenantId,command.proceedingId,command.itemCode):null,evaluation=command.action==="assess"?await buildProceedingEvaluation(command.tenantId,command.proceedingId):undefined,decision=decideProceeding({context,raw:command,exists:Boolean(proceeding),item,evaluation}),persistence=await persistProceeding({...decision,actor,evaluation});return Response.json({event:decision.event,persistence,...await proceedingProjection(command.tenantId,command.matterId),limitation});}catch(e){if(e instanceof RateLimitError)return rateLimitResponse(e);if(e instanceof RequestSecurityError)return Response.json({error:"Untrusted request origin"},{status:403});if(e instanceof AuthorizationError)return Response.json({error:"Access denied"},{status:403});return Response.json({error:e instanceof Error?e.message:"Proceeding command failed"},{status:400});}}
